### ISSUE TITLE
bad gateway in jquery download

### ISSUE THREAD

**Issue by shajisnanu** [jquery/download.jqueryui.com#459] opened 2020-05-19 15:18 UTC
Can not download the Autocomplete

**Comment by rtconner** [comment] 2020-05-19 15:58
this is a duplicate of https://github.com/jquery/download.jqueryui.com/issues/390

**Comment by Nkanyi** [comment] 2020-05-20 00:58
could nt download

**Comment by fnagel** [comment] 2020-05-25 08:58
Duplicate of #359

**Closed by fnagel** 2020-05-25 08:58 UTC
