### ISSUE TITLE
Error bad gateway

### ISSUE THREAD

**Issue by Jerocam** [jquery/download.jqueryui.com#442] opened 2020-04-20 03:10 UTC
Hello, I cannot download from the gallery for themes..Check it. Thanks

**Comment by pieceofbryce** [comment] 2020-04-20 04:27
+1

**Comment by thomasFoglia** [comment] 2020-04-20 08:33
+1

**Comment by yafiesetyo** [comment] 2020-04-20 12:46
+1

**Comment by HobieCat** [comment] 2020-04-20 14:42
+1

**Comment by nexenator** [comment] 2020-04-22 07:33
+1

**Comment by fnagel** [comment] 2020-04-22 09:05
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:05 UTC

**Comment by msandi** [comment] 2020-04-22 12:50
I'm getting the 502 error now (and very early this morning too)
