### ISSUE TITLE
502 Error Reported !!!

### ISSUE THREAD

**Issue by RaNeSa** [jquery/download.jqueryui.com#492] opened 2020-06-21 04:43 UTC
Hi ... I can not download  jQuery UI .... Because it  is reported error 502 !!!!!!!

**Comment by bpospanov** [comment] 2020-06-22 12:10
https://jqueryui.templersmc.net/download/#!

**Comment by fnagel** [comment] 2020-06-25 11:26
Duplicate of #359

**Closed by fnagel** 2020-06-25 11:26 UTC
