### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by lalandeepak** [jquery/download.jqueryui.com#520] opened 2020-07-30 07:43 UTC
I want to download but getting HOST error. Please provide me a genuine links.
Thanks
Deepak
deepaklalankumar@gmail.com

**Comment by RobertDickey** [comment] 2020-07-30 15:32
This is still happening 8 hours later.

**Comment by zachakbar** [comment] 2020-07-30 17:19
Still happening for me

**Comment by matrentman** [comment] 2020-07-30 19:11
Still happening, someone please fix.

**Comment by topmonroe9** [comment] 2020-07-30 22:26
Still not able to download

**Comment by fnagel** [comment] 2020-08-04 12:01
Duplicate of #359

**Closed by fnagel** 2020-08-04 12:01 UTC
