### ISSUE TITLE
502 error trying to download plain vanilla jQuery UI

### ISSUE THREAD

**Issue by JonathanHayward** [jquery/download.jqueryui.com#515] opened 2020-07-22 11:59 UTC
Error 502 Ray ID: 5b6cfcf28b0203b4 • 2020-07-22 11:58:07 UTC
Bad gateway
You
Browser
Working
Chicago
Cloudflare
Working
download.jqueryui.com
Host
Error
What happened?
The web server reported a bad gateway error.

What can I do?
Please try again in a few minutes.

Cloudflare Ray ID: 5b6cfcf28b0203b4 • Your IP: 73.74.173.201 • Performance & security by Cloudflare

**Comment by fnagel** [comment] 2020-07-22 12:02
Duplicate of #359

**Closed by fnagel** 2020-07-22 12:02 UTC
