### ISSUE TITLE
 Jquery ui download builder is broken

### ISSUE THREAD

**Issue by ErnestoPaz** [jquery/download.jqueryui.com#527] opened 2020-08-05 15:50 UTC
I am wondering if the jquery ui download builder is broken.
I have used it many times before, but now it doesn't seem to be working.

I untick all the stuff I click the button at the bottom marked download and sent me to this link https://download.jqueryui.com/download and the page shows and error message.

**Comment by ABlack990** [comment] 2020-08-05 19:09
#390 looks like it's been an issue for a while.  Not sure when it's going to be fixed, but this thread has a response a ways down that offers a solution

**Comment by quitequinn** [comment] 2020-08-07 03:52
https://jqueryui.templersmc.net/download/

**Comment by fnagel** [comment] 2020-08-07 15:06
Duplicate of #359

**Closed by fnagel** 2020-08-07 15:06 UTC
