### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by AribSheikh** [jquery/download.jqueryui.com#541] opened 2020-09-06 18:04 UTC
Ray ID: 5cea1b695bbb14dd • 2020-09-06 18:03:30 UTC
Can't download JQuery ui

**Comment by BychkovVV** [comment] 2020-09-07 13:23
I have this problem too.
Thank you in advance!

**Comment by khaledmostafaismaiel** [comment] 2020-09-07 19:31
me too

**Comment by Cirunz** [comment] 2020-09-08 13:40
Same here

**Comment by luismigil** [comment] 2020-09-08 17:29
same here

**Comment by Jahnavi-21** [comment] 2020-09-09 10:40
Same Here

**Comment by Gofer01** [comment] 2020-09-09 15:57
So everyone is having the same problem. So who on the jQuery team is assigned to fix the download issue?

**Comment by fnagel** [comment] 2020-09-21 21:31
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:31 UTC
