### ISSUE TITLE
Unable to download 1.9.2 Theme

### ISSUE THREAD

**Issue by Tek-Wyatt** [jquery/download.jqueryui.com#427] opened 2020-03-09 23:26 UTC
Greetings,

I am unable to download a 1.9.2 theme. Tried for about a week now and not sure whats going on.

https://jqueryui.com/themeroller/#!zThemeParams=5d000001001306000000000000003d8888d844329a8dfe02723de3e5701258a13d5ba490adca99e4a02bf259c3083bccd292fbc7a815b30f470ff7864f8c0d0abbfd0926063d26d115eb0a5af33202d9000fc77557b5eaadab27d4e9cfb6afc2055fea7893986242328d3d52c35bc8c7046868c043bc14788df4410a9b383e1c3db00d09e99ac3f7e7afff39b61419d279b5f764dfe7a3c99e38e8446a1a02bfe7bbf023a6946e05cf78d7fb44eb43e69ac945a3a94bde771131b42084d769ddd8ee2d81d4bdd8a0ea0fd31a8ee2120a2f3296b754f7218ce69f1e0c14ae9a04dc22b35dfe2f9ceac84063449913ce3c22f482fd08aa92fe03da393a6c37e5ba33d9693fec1ef1169ba5bbe3fe655b609cf27077d3719fc1adea69e6861fbc68ee497e556ceef9a150c61e8e18791afe42dfd949081a2e38821d4128168c778110585e4fe33ee8283a7f782d0b260ac138c245edabc5df96d82aab83cb273127e8ba12f41aef53002a25d67dbcac9396463ad10ca66d3eb5fce2329a86e2c947674a6aaff56eee9fcaf47f45d19cf3f72e13492daf252adc138fd32f323c70f898992b8b954fe667ee58bb341bba314f01c55d500cdab9117325cf9e1ed3e4bef321ccd66126d6725e2a01b403696252b181dbd5ecf89b1e29e6f34f241f8249cac903459bde06e9c63aff9517909a

**Comment by fnagel** [comment] 2020-03-10 09:20
Duplicate of #359

**Closed by fnagel** 2020-03-10 09:20 UTC
