### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by zakstark** [jquery/download.jqueryui.com#530] opened 2020-08-12 19:01 UTC
Hi there, I'm getting an Error 502 bad gateway when trying to use... https://jqueryui.com/download/
....no matter what widgets I choose to download.

**Comment by all-your-base** [comment] 2020-08-12 22:45
I can confirm, the download link doesn't work; it shows a Cloudflare error page.

**Comment by leckman** [comment] 2020-08-12 23:52
also experiencing this problem

**Comment by winglovecola** [comment] 2020-08-13 00:14
Hello also receive this error. Please look into it. Thanks

**Comment by AuctionArmsCEO** [comment] 2020-08-13 02:28
Error 502 at https://download.jqueryui.com/download - Doesn't matter what configuration is attempted.

**Comment by mfhassan22** [comment] 2020-08-13 06:47
i am also getting 502 error

**Comment by anastasia-son** [comment] 2020-08-13 09:13
I have the same issue - Error 502

**Comment by TensorTom** [comment] 2020-08-13 15:31
same

**Comment by mran3** [comment] 2020-08-13 16:37
same

**Comment by demirmusa** [comment] 2020-08-14 12:28
same

**Comment by Vic40k** [comment] 2020-08-14 13:31
same

**Comment by ShahManali99** [comment] 2020-08-14 14:46
> Hi there, I'm getting an Error 502 bad gateway when trying to use... https://jqueryui.com/download/
> ....no matter what widgets I choose to download.

Facing same issue

**Comment by tekdru** [comment] 2020-08-14 17:23
I'm having the same problem when trying to download a custom package.

**Comment by schmelik** [comment] 2020-08-14 21:23
bump

**Comment by leckman** [comment] 2020-08-14 23:38
You can use this mirror to download: https://github.com/jquery/download.jqueryui.com/issues/384#issuecomment-621833464

**Comment by tekdru** [comment] 2020-08-27 18:16
Thank you!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ShahManali99** [comment] 2020-08-27 19:10
> You can use this mirror to download: [#384 (comment)](https://github.com/jquery/download.jqueryui.com/issues/384#issuecomment-621833464)

Thank you :)

**Comment by fnagel** [comment] 2020-08-28 23:32
Duplicate of #359

**Closed by fnagel** 2020-08-28 23:32 UTC
