### ISSUE TITLE
Can't download customized version

### ISSUE THREAD

**Issue by Zempheroth** [jquery/download.jqueryui.com#454] opened 2020-05-13 08:18 UTC
Select required components in builder, click Download - Cloudflare 
got 
![image](https://user-images.githubusercontent.com/5180270/81788558-6337c680-950b-11ea-87df-d4effce420fd.png)

**Comment by XavLal** [comment] 2020-05-13 13:09
Hi, same issue !

**Comment by sebastianbustos** [comment] 2020-05-14 07:42
Same...

**Comment by radioman-00** [comment] 2020-05-14 08:11
same issue on 14-5-2020

**Comment by SIMSON20** [comment] 2020-05-14 10:34
Hi! same issue...

**Comment by PatriotDevOps** [comment] 2020-05-14 14:58
Same issue blocking some work

**Comment by brendan8c** [comment] 2020-05-15 07:52
I also can not download.
Same problem.

**Comment by fnagel** [comment] 2020-05-15 13:39
Duplicate of #359

**Closed by fnagel** 2020-05-15 13:39 UTC
