### ISSUE TITLE
ThemeRoller - quirks/broken

### ISSUE THREAD

**Issue by thezoggy** [jquery/download.jqueryui.com#195] opened 2014-02-03 21:06 UTC
Using Firefox 26 on Windows 7 64bit

Went to my jquery ui 1.10.3 customize link, http://pastebin.com/raw.php?i=m3c8c0nG
On the left panel, click on 'Font Settings' then move your mouse down to the next section, you will see the font settings panel open and close in a loop. 

If you close the section and reopen its fine. Refresh the page, you will notice only the 'font settings' does this, as the other sections are fine if you open them.

**Comment by jzaefferer** [comment] 2015-01-27 16:32
Unable to reproduce, closing.

**Closed by jzaefferer** 2015-01-27 16:32 UTC
