### ISSUE TITLE
Error 502- Download broken

### ISSUE THREAD

**Issue by virmix** [jquery/download.jqueryui.com#488] opened 2020-06-13 13:31 UTC
Error 502 Ray ID: 5a2c24c68d3dff58 • 2020-06-13 13:26:30 UTC
Bad gateway

https://download.jqueryui.com/download

**Comment by skolsen1** [comment] 2020-06-13 18:00
Getting the same thing.

**Comment by Lajull** [comment] 2020-06-14 10:09
Broken for me too :/

**Comment by Mbotes** [comment] 2020-06-15 05:59
its broken, both for custom a complete package download

**Comment by getangar** [comment] 2020-06-15 07:41
Same behavior for me.

**Comment by LeLampadaire** [comment] 2020-06-15 19:34
Same thing...

**Comment by sarojupa** [comment] 2020-06-15 21:41
Still getting 502

**Comment by synfinatic** [comment] 2020-06-16 00:57
+1

**Comment by Osempu** [comment] 2020-06-16 04:22
Broken link! :(

**Comment by scott-fisher-iii** [comment] 2020-06-16 14:27
Same here

**Comment by jtsSTECH** [comment] 2020-06-16 19:11
same.

**Comment by allanemerson** [comment] 2020-06-17 17:34
Same. It's been this way for a while.

**Comment by nageshraoj** [comment] 2020-06-19 05:51
Getting same error. It looks like it has been for while. Any solution? 
![Capture](https://user-images.githubusercontent.com/19434056/85100979-053f8280-b21f-11ea-9e44-852fad76b348.JPG)

**Comment by magicsunday** [comment] 2020-06-19 10:00
Try https://jqueryui.templersmc.net/download#!version=1.12.1&components=110000010001000001100000110010000000000000000000

**Comment by nageshraoj** [comment] 2020-06-19 10:12
@magicsunday Thank you so much. It is working for me.

**Comment by kasunvp** [comment] 2020-06-19 13:52
Still get a 502 from https://download.jqueryui.com/.

**Comment by bpospanov** [comment] 2020-06-22 12:10
https://jqueryui.templersmc.net/download/#!

**Comment by fnagel** [comment] 2020-06-25 11:25
Duplicate of #359

**Closed by fnagel** 2020-06-25 11:25 UTC
