### ISSUE TITLE
Error 502 with downloading

### ISSUE THREAD

**Issue by alexeygorin** [jquery/download.jqueryui.com#535] opened 2020-08-28 19:14 UTC
Hi. I've attempted to download jqueryui on the page https://jqueryui.com/download/
It redirects me to https://download.jqueryui.com/download
With error message Error 502 Ray ID: 5ca05407784b3f04 • 2020-08-28 19:09:43 UTC 
Hope it useful.
Best, Alex

**Comment by fnagel** [comment] 2020-08-28 23:33
Duplicate of #359

**Closed by fnagel** 2020-08-28 23:33 UTC
