### ISSUE TITLE
Can't download any theme for jquery ui 1.11.4 version

### ISSUE THREAD

**Issue by AlexPex** [jquery/download.jqueryui.com#326] opened 2016-07-19 07:31 UTC
I tried to download several themes but always get the same message:
Error 504.

**Comment by suemag832** [comment] 2016-07-19 12:45
Same here, keep getting error - 
download.jqueryui.com
Host
Error

**Comment by scottgonzalez** [comment] 2016-07-19 13:15
Duplicate of #313.

**Closed by scottgonzalez** 2016-07-19 13:15 UTC
