### ISSUE TITLE
impossible to download jQueryUI from site Error 502

### ISSUE THREAD

**Issue by maxcann76** [jquery/download.jqueryui.com#543] opened 2020-09-10 09:37 UTC
1- from: https://jqueryui.com/download/ I click download button
2- I receive: Error 502 Ray ID: 5d08271a1bfd6f64 • 2020-09-10 09:34:22 UTC
Bad gateway

**Comment by Corcules** [comment] 2020-09-10 10:04
Same

**Comment by eriksaetren** [comment] 2020-09-11 08:13
Same :( Sad panda

**Comment by wert90** [comment] 2020-09-14 01:58
maybe this link help you

https://jqueryui.com/download/all/

**Comment by fnagel** [comment] 2020-09-21 21:31
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:31 UTC
