### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by Brinzaniuc** [jquery/download.jqueryui.com#428] opened 2020-03-10 07:14 UTC
![Annotation 2020-03-10 091927](https://user-images.githubusercontent.com/44940155/76288590-c0b35b00-62af-11ea-8909-f667545b695a.png)
502 bad gateway

**Comment by fnagel** [comment] 2020-03-10 09:20
Duplicate of #359

**Closed by fnagel** 2020-03-10 09:20 UTC
