### ISSUE TITLE
Error 502 bad gateway when trying to download

### ISSUE THREAD

**Issue by ketan808** [jquery/download.jqueryui.com#398] opened 2019-11-11 16:34 UTC
Error 502 bad gateway been like this for three days

**Comment by WhitewaterDave** [comment] 2019-11-12 21:39
I'm not one of the developers. This error has been going on for some time. You can download jqueryui using the quick download links on the builder page. It under the thick light gray line under Builder. You can use it until they get the problem fixed. 
![jquery-screenshot](https://user-images.githubusercontent.com/8185773/68713049-f8f99580-056a-11ea-9625-1ee3871c2fec.png)

**Comment by KevinWaterson** [comment] 2019-11-21 05:53
Error 502 Ray ID: 53906626ae27df99 • 2019-11-21 05:52:42 UTC
Bad gateway

**Comment by fnagel** [comment] 2020-02-18 17:49
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:49 UTC
