### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by mgjovero-github** [jquery/download.jqueryui.com#502] opened 2020-07-08 09:24 UTC
Error 502 Ray ID: 5af8bc89f9660a98 • 2020-07-08 09:21:42 UTC
Bad gateway

**Comment by RangoSn** [comment] 2020-07-08 23:41
Use this dude https://jqueryui.templersmc.net/

**Comment by mgjovero-github** [comment] 2020-07-09 07:50
Thanks much 😊.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RangoSn** [comment] 2020-07-11 07:49
Try to download a stable version, I think the problem is when we try to download a custom version.
It work for me.

**Comment by fnagel** [comment] 2020-07-20 07:47
Duplicate of #359

**Closed by fnagel** 2020-07-20 07:47 UTC
