### ISSUE TITLE
Custom download not working. Shows error msg

### ISSUE THREAD

**Issue by NamyeVinayak** [jquery/download.jqueryui.com#325] opened 2016-07-19 07:25 UTC
![image](https://cloud.githubusercontent.com/assets/14541740/16941823/1a944a1c-4db0-11e6-81bc-9dc54bdcc636.png)

**Comment by scottgonzalez** [comment] 2016-07-19 13:24
Duplicate of #313.

**Comment by UTCWebDev** [comment] 2016-07-19 13:37
I'm getting a 502 Gateway time-out host error reported from CloudFlare CDN.

![screen-shot 2016-07-19 at 9 37 00 am](https://cloud.githubusercontent.com/assets/2539685/16951758/6413ed26-4d94-11e6-9df5-8a313e2f020f.png)

**Comment by martilo** [comment] 2016-07-20 08:32
I'm also getting the Error 504 unable to connect to host download.jqueryui.com

**Comment by hbowman98** [comment] 2016-07-20 13:50
Not working for me either. It appears the "Theme" section of the page is not loading and just causes the page to hang. I need a custom version and this is delaying my project, any word on when this will be fixed?

**Comment by scottgonzalez** [comment] 2016-07-20 13:52
Please stop posting me too comments. We know it's not working. Follow #313.

**Closed by scottgonzalez** 2016-07-20 13:52 UTC
