### ISSUE TITLE
Impossible customize UI theme and download it

### ISSUE THREAD

**Issue by msamarek** [jquery/download.jqueryui.com#544] opened 2020-09-13 16:13 UTC
It looks that nobody has not will to resolve issue with UI theme builder.
Does anybody know if there is any alternative to build new theme for JQuery?
Thank you very much,

**Comment by fnagel** [comment] 2020-09-21 21:31
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:31 UTC

**Comment by msamarek** [comment] 2020-09-22 07:05
I understand. It looks that themeroller died forever.
