### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by hectordufau** [jquery/download.jqueryui.com#501] opened 2020-07-07 14:01 UTC
Error 502 Ray ID: 5af218354a68f607 • 2020-07-07 14:00:56 UTC
Bad gateway

**Comment by RangoSn** [comment] 2020-07-08 23:41
Use https://jqueryui.templersmc.net/

**Comment by RangoSn** [comment] 2020-07-11 07:48
Try to download a stable version, I think the problem is when we try to download a custom version.
It work for me.

**Comment by fnagel** [comment] 2020-07-20 07:47
Duplicate of #359

**Closed by fnagel** 2020-07-20 07:47 UTC
