### ISSUE TITLE
Error 502 when attempting to download custom JQueryUI package

### ISSUE THREAD

**Issue by jaysunwalter123** [jquery/download.jqueryui.com#546] opened 2020-09-16 10:56 UTC
The error appears in the console and then again when attempting to download the package. The page doesn't appear to be fully loading in the first place, i.e. the Theme section at the bottom seems to not have loaded.

**Comment by gergel0304** [comment] 2020-09-17 17:22
Have the same problem

**Comment by jamesrosssharp** [comment] 2020-09-18 03:41
Same here - bad gateway

**Comment by philfrei** [comment] 2020-09-18 04:53
Add me to the list. Was just trying to download the datepicker.

**Comment by spunktonline** [comment] 2020-09-18 08:07
Same here - bad gateway

**Comment by samjgarnham** [comment] 2020-09-18 09:06
Same here for the last year - was #369

**Comment by fnagel** [comment] 2020-09-21 21:32
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:32 UTC
