### ISSUE TITLE
Revert to 1.11 default theme

### ISSUE THREAD

**Issue by jzaefferer** [jquery/download.jqueryui.com#283] opened 2015-10-29 14:56 UTC
I tagged and published 2.1, which went live, and while jqueryui.com still uses 2.0.x, which doesn't include 1.12, the default theme changed to Base on http://jqueryui.com/download/ anyway. I don't want to make a mess with retagging old tags as new, and don't see how to otherwise revert this.

I looked into the change required to switch back to the 1.11 default theme for the download page, but couldn't figure out where that's coming from. It still works fine for TR: http://jqueryui.com/themeroller/ - also when clicking on Download Theme on that page, it selects Smoothness. TR doesn't even list the Base theme, unlike the download page.

**Comment by rxaviers** [comment] 2015-10-31 00:55
It seems like the code in master is correct, but the problem is that the live site shouldn't use it yet. If that's the case, I think retagging old tags as new is the best approach to "revert" this situation. I would revert commits in master if such commits were actually wrong.

PS: There's a chance I am misinterpreting this, so please just let me know.

**Comment by jzaefferer** [comment] 2015-10-31 13:14
I needed that new release to test the jQuery UI release script. Retagging will just break that again.

Is there a reasonable way to revert to the old default theme until 1.12 is stable?

**Comment by rxaviers** [comment] 2015-10-31 23:02
The theme updated has been tracked by #248, landed by e617430938ed83ca3607475f8642dd0b4f5fc731.

**Comment by jzaefferer** [comment] 2015-11-02 15:46
Those changes all seem fine, except https://github.com/jquery/download.jqueryui.com/commit/e617430938ed83ca3607475f8642dd0b4f5fc731#diff-3910a263174d7c78244ba4d881eaac91 (updating `lib/themeroller-themegallery.js`). Since that updated a theme, instead of adding a new one, I'm still unsure how to revert that without breaking 1.12.

**Comment by scottgonzalez** [comment] 2016-03-08 16:02
This was dealt with.

**Closed by scottgonzalez** 2016-03-08 16:02 UTC
