### ISSUE TITLE
Error 502 Ray ID: 5732932dbb642cc1 • 2020-03-13 03:12:44 UTC Bad gateway

### ISSUE THREAD

**Issue by shahrul91** [jquery/download.jqueryui.com#429] opened 2020-03-13 03:13 UTC
Unable to download theme roller.

**Comment by shahrul91** [comment] 2020-03-13 03:13
Also got issue, when fill in the hexa color, the theme roller not reflect the exact changes.

**Comment by Bentley34** [comment] 2020-03-13 08:40
I have the same problem and read on the previous post that this occurred six months ago and was slowly being repaired. Can I ask have you used it before? I'm wondering if it has not been working for six months. I have never used it before.

**Comment by hgnjpac** [comment] 2020-03-19 16:59
I've used it a few times in the past, over the years - the last time was a year or so ago.  This is the first time I've had an issue.  I'm also unable to download.

**Comment by peci** [comment] 2020-03-23 17:56
Error 502 Ray ID: 578a06d5bd39d248 • 2020-03-23 17:56:01 UTC

**Comment by fnagel** [comment] 2020-03-23 20:55
Duplicate of #359

**Closed by fnagel** 2020-03-23 20:55 UTC
