### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by dimor22** [jquery/download.jqueryui.com#504] opened 2020-07-08 18:26 UTC
BAD GATEWAY 

Ray ID: 5afbd9b07b6b6dca • 2020-07-08 18:25:53 UTC

**Comment by RangoSn** [comment] 2020-07-08 23:43
maybe this will help you https://jqueryui.templersmc.net/

**Comment by HuyNguyen206** [comment] 2020-07-10 08:10
> maybe this will help you https://jqueryui.templersmc.net/

Hi RangoSn,

All Package JqueryUI in that page seem to miss quite a lot of thing that include (html, css, images)
For example: When I use the dialog function, the dialog appears without the "Close" button

**Comment by RangoSn** [comment] 2020-07-11 07:46
Hi @HuyNguyen206 
Thanks for the comment, I am just getting started and for now it worked for me, however I think the problem is when I try to download a personality version, when I download the stable version it has no problem

**Comment by HuyNguyen206** [comment] 2020-07-13 11:25
> Hi @HuyNguyen206
> Thanks for the comment, I am just getting started and for now it worked for me, however I think the problem is when I try to download a personality version, when I download the stable version it has no problem

Hi @RangoSn 
Thank you.
In my case, the issue is JS from Bootstrap override the code in Jquery UI JS. After I change the order of the JS file, It works well.

**Comment by fnagel** [comment] 2020-07-20 07:47
Duplicate of #359

**Closed by fnagel** 2020-07-20 07:47 UTC
