### ISSUE TITLE
Donwload page (Builder) - Unable to select theme

### ISSUE THREAD

**Issue by luyzk7** [jquery/download.jqueryui.com#464] opened 2020-05-25 01:35 UTC
Unable to select theme when using download builder page: https://jqueryui.com/download/
![Screenshot_2020-05-24 Download Builder jQuery UI](https://user-images.githubusercontent.com/38673439/82770400-a6d8dd00-9df5-11ea-9eb8-19b73cbfe7d9.png)

**Comment by fnagel** [comment] 2020-05-25 08:57
Duplicate of #359

**Closed by fnagel** 2020-05-25 08:57 UTC
