### ISSUE TITLE
Cannot download theme site down Error 502 Ray ID: 5cdfa6bad945069a • 2020-09-05 11:36:13 UTC Bad gateway

### ISSUE THREAD

**Issue by seanshonagh** [jquery/download.jqueryui.com#540] opened 2020-09-05 11:36 UTC
You
Browser
Working
London
Cloudflare
Working
download.jqueryui.com
Host
Error

**Comment by fnagel** [comment] 2020-09-21 21:30
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:30 UTC
