### ISSUE TITLE
Download builder not working

### ISSUE THREAD

**Issue by bergschold** [jquery/download.jqueryui.com#414] opened 2020-01-22 08:22 UTC
I When I click the download button I get an error page

**Comment by ashleefoureyes** [comment] 2020-01-22 18:57
Confirming the above. Get Bad Gateway error (502). Seems to be on and off - will work for a few minutes and then reset to default and users will be unable to edit or download.

**Comment by mr-stivo** [comment] 2020-01-24 07:06
Same problem. Cannot choose a theme and clicking download gives Bad Gateway error (502).

**Comment by fnagel** [comment] 2020-02-18 17:51
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:51 UTC
