### ISSUE TITLE
 Error 502 Ray ID: 5bc855d5c8ab4da5 • 2020-08-02 14:02:13 UTC Bad gateway

### ISSUE THREAD

**Issue by yancha38** [jquery/download.jqueryui.com#524] opened 2020-08-02 14:03 UTC
Not Able to download it.

**Comment by mehmoodahsan625** [comment] 2020-08-03 16:47
Why i am be able to download it.

**Comment by mehmoodahsan625** [comment] 2020-08-03 16:48
that show me host error.

**Comment by fnagel** [comment] 2020-08-04 12:02
Duplicate of #359

**Closed by fnagel** 2020-08-04 12:02 UTC
