### ISSUE TITLE
ERROR 502 BADGATEWAY

### ISSUE THREAD

**Issue by MindPower99** [jquery/download.jqueryui.com#400] opened 2019-11-29 23:16 UTC
ERROR 502 BADGATEWAY

**Comment by femke77** [comment] 2019-12-03 00:53
Still happening today.

**Comment by ryanlaws** [comment] 2019-12-04 15:11
Still happening.

**Comment by tomvanlier** [comment] 2019-12-06 09:21
And still happening

**Comment by WulleBulle** [comment] 2019-12-06 13:53
Error 502 Ray ID: 540ebc42e9a67cfa • 2019-12-06 13:51:35 UTC
Bad gateway

Nearly everyday. What's happening to Github since it was annected by MS? It gets worser.....

**Comment by xobrooklynn** [comment] 2019-12-08 01:35
I keep having the same issue as well.

**Comment by radioman-00** [comment] 2019-12-09 12:40
still cannot download

**Comment by fnagel** [comment] 2020-02-18 17:50
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:50 UTC
