### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by YanlanCai** [jquery/download.jqueryui.com#421] opened 2020-02-16 11:26 UTC
![error](https://user-images.githubusercontent.com/22871833/74603807-43eaf200-50f2-11ea-8c70-64b6a0517e1e.png)

**Comment by rikkilake** [comment] 2020-02-17 15:21
Same today.

**Comment by Bevilh2o** [comment] 2020-02-18 13:37
Still the same

**Comment by fnagel** [comment] 2020-02-18 17:53
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:53 UTC
