### ISSUE TITLE
Download Builder not work

### ISSUE THREAD

**Issue by kefywk** [jquery/download.jqueryui.com#457] opened 2020-05-17 16:00 UTC
This is the error Error 502 Ray ID: 594e8c34da27d618 • 2020-05-17 15:59:48 UTC
Bad gateway

https://download.jqueryui.com/download

**Comment by mijiapps** [comment] 2020-05-18 11:54
Same.

**Comment by tgrahn2** [comment] 2020-05-18 12:29
same

**Comment by spacemanjan** [comment] 2020-05-18 14:21
same

**Comment by mijiapps** [comment] 2020-05-18 14:38
I built the project locally and was able to generate a custom build. This is probably the best solution for now.

**Comment by d-signet** [comment] 2020-05-19 10:42
Not always possible.

Project does not build on windows machines, for example

 Unsupported platform for modern-syslog@1.1.2: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Tiahin** [comment] 2020-05-19 20:19
Please remove `npm-shrinkwrap.json` and try `npm i -f`

**Comment by fnagel** [comment] 2020-05-25 08:58
Duplicate of #359

**Closed by fnagel** 2020-05-25 08:58 UTC
