### ISSUE TITLE
Getting 502 error when trying to download jqueryui bundle

### ISSUE THREAD

**Issue by sanyogitapandey7** [jquery/download.jqueryui.com#548] opened 2020-09-23 12:40 UTC
running into 502 error page when trying to download the jqueryui bundle from **https://download.jqueryui.com/download**
Attached is the error screenshot
![image](https://user-images.githubusercontent.com/4893368/94013701-0eb12b80-fdc8-11ea-8086-5088f37c8e46.png)

**Comment by aKelleter** [comment] 2020-09-24 08:50
I confirm this issue. 
Thanks a lot.

**Comment by PlaXiva** [comment] 2020-09-24 09:38
Me to

**Comment by westjac** [comment] 2020-09-24 16:34
I am also getting this issue

**Comment by daprezjer** [comment] 2020-09-28 05:24
@fnagel , apologies for pinging directly, but since no one is giving a status update on this significant issue, hoping you can.

**Comment by sanyogitapandey7** [comment] 2020-09-28 17:32
Issue still exists :(

**Comment by icemagno** [comment] 2020-10-02 04:22
Well... I think I must stop my work and wait these guys go to solve this problem. Anyone wants a coffe ?

**Comment by fnagel** [comment] 2020-10-06 11:06
Duplicate of #359

**Closed by fnagel** 2020-10-06 11:06 UTC
