### ISSUE TITLE
Error 502 Ray ID: 57e0bf0438fafb94 • 2020-04-03 06:31:21 UTC

### ISSUE THREAD

**Issue by sarahk** [jquery/download.jqueryui.com#435] opened 2020-04-03 06:32 UTC
error accessing themes from Auckland, NZ

file: https://download.jqueryui.com/download/theme?callback=jQuery111301835671173878426_1585895449847&_=1585895449848

https://jqueryui.com/download/

**Comment by goozak** [comment] 2020-04-13 13:11
See [Issue Thread Regarding the 502 Error #390](https://github.com/jquery/download.jqueryui.com/issues/390)

**Comment by fnagel** [comment] 2020-04-22 09:04
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:04 UTC
