### ISSUE TITLE
ThemeRoller not updating

### ISSUE THREAD

**Issue by BeanyTheSane** [jquery/download.jqueryui.com#378] opened 2019-10-08 01:36 UTC
I can view the default and several themes but if I change anything it reverts to a plain state and refuses to update for anything after that.

**Comment by ginsingtome** [comment] 2019-10-13 03:10
I get exactly the same thing.

**Comment by NcMichel** [comment] 2019-10-22 08:03
same here.

**Comment by honsberg** [comment] 2019-10-22 18:58
can someone fix this?

**Comment by honsberg** [comment] 2019-10-24 09:27
you can use this themeroller: https://jqueryui.templersmc.net/themeroller

**Comment by NcMichel** [comment] 2019-10-24 22:03
thanks for the job, it seems to work.

**Comment by fnagel** [comment] 2020-02-18 17:47
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:47 UTC
