### ISSUE TITLE
Autocomplete jquery download builder goes on 504  timeout

### ISSUE THREAD

**Issue by unixforce** [jquery/download.jqueryui.com#318] opened 2016-07-13 11:24 UTC
Hello, when I jave just selected only "autocomplete" plugin && download with jquery 1.12.0(Stable, for jQuery1.7+) server goes on timeout server 504. Anyone have same issue ??

**Comment by jzaefferer** [comment] 2016-07-13 11:37
Duplicate of #313.  Please give us some time to address these known issues.

**Closed by jzaefferer** 2016-07-13 11:37 UTC

**Comment by unixforce** [comment] 2016-07-13 13:17
Ok, thanks a lot in advance.
