### ISSUE TITLE
Error 502 when downloading

### ISSUE THREAD

**Issue by chezaresarmiento** [jquery/download.jqueryui.com#514] opened 2020-07-21 02:24 UTC
Error 502 when downloading

**Comment by atstockland** [comment] 2020-07-21 02:39
At the top of the download page, click on the quick link for "Stable"

**Comment by stef011** [comment] 2020-07-21 09:58
Same for me, I only want to download the 'autocomplete' widget...

**Comment by fnagel** [comment] 2020-07-22 12:02
Duplicate of #359

**Closed by fnagel** 2020-07-22 12:02 UTC
