### ISSUE TITLE
 Error 502 - Bad gateway - 2020-07-31 14:46:24 UTC

### ISSUE THREAD

**Issue by cassianoheitor1993** [jquery/download.jqueryui.com#522] opened 2020-07-31 14:52 UTC
![image](https://user-images.githubusercontent.com/68757208/89046538-78aad880-d323-11ea-9c85-6ae70e12ea95.png)

What's happening? I'm trying download JQuery 1.12.1 (Stable, for jQuery1.7+) since last week and this error remains.

Thanks!

**Comment by fnagel** [comment] 2020-08-04 12:02
Duplicate of #359

**Closed by fnagel** 2020-08-04 12:02 UTC
