### ISSUE TITLE
Download error 504 on all 1.9.2 ThemeRoller themes

### ISSUE THREAD

**Issue by jdamato25** [jquery/download.jqueryui.com#432] opened 2020-03-27 13:39 UTC
trying to download some ThemeRoller themes and I'm getting Eror 504 after about of minute of it trying to download. My particular app requires version 1.9.2 Any help on this would be greatly appreciated.

**Comment by ddison** [comment] 2020-04-09 22:53
I have this same issue, the app I have requires 1.9.x and anything I try to download gives Error 504:

Error 504 Ray ID: 5817cb4f8bc9fdd1 • 2020-04-09 22:51:41 UTC
Gateway time-out

Says the Browser is working, Cloudflare is working, but a Host error at download.jqueryui.com

**Comment by goozak** [comment] 2020-04-13 13:12
See [Issue Thread Regarding the 502 Error #390](https://github.com/jquery/download.jqueryui.com/issues/390)

**Comment by fnagel** [comment] 2020-04-22 09:03
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:03 UTC
