### ISSUE TITLE
Theme Roller Not Working

### ISSUE THREAD

**Issue by sbarker13cuisineandtravel** [jquery/download.jqueryui.com#566] opened 2020-11-11 16:19 UTC
I cannot get any of the tabs to open on the theme roller to be able to edit them.

**Comment by mgol** [comment] 2020-11-12 22:58
Thanks for the report. Until that's fixed, you can use https://download.jqueryui.com/themeroller/.

**Comment by StonehengeCreations** [comment] 2020-11-18 20:06
The problem is that farbtastic.css and farbtastic.js cannot be found.
Please solve this, as this alternative url is hard to find.

**Comment by knubew** [comment] 2020-11-21 13:38
Hell, it took me 2 hours to finally find this alternative URL.

You should at least post a note on the page [https://download.jqueryui.com/themeroller/](https://jqueryui.com/themeroller/) that the functionality of the Theme Roller is currently disrupted and specify the alternative Theme Roller URL [https://download.jqueryui.com/themeroller/](https://download.jqueryui.com/themeroller/) for the users.

**Comment by mgol** [comment] 2020-11-21 22:12
I think I fixed the issue but we have issues with too long Cloudflare caches. I'll reopen until the cache refreshes or until I figure out how to trigger it faster.

**Comment by mgol** [comment] 2020-11-21 22:38
It seems to work now, closing again.

**Closed by mgol** 2020-11-21 22:38 UTC

**Comment by knubew** [comment] 2020-11-22 13:12
Thank you very much for fixing it.

**Comment by sbarker13cuisineandtravel** [comment] 2021-01-08 17:00
Hi Do you know how to remove the icons from the download? They are slowing
down my site and I only use the accordion and tab function which do not
need the icons.
