### ISSUE TITLE
Bad gateway, Error 502

### ISSUE THREAD

**Issue by leonelsonpalima** [jquery/download.jqueryui.com#440] opened 2020-04-17 01:24 UTC
No puedo descargar 
![screenshot 314](https://user-images.githubusercontent.com/21249438/79522053-51542800-8020-11ea-8e3b-b5cd110bbf8f.jpg)

**Comment by fnagel** [comment] 2020-04-22 09:05
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:05 UTC
