### ISSUE TITLE
Error 502 when download 

### ISSUE THREAD

**Issue by dhuynh08t4** [jquery/download.jqueryui.com#500] opened 2020-07-06 12:28 UTC
After select some options. then click download, Error 502 display
Here is my link 
https://jqueryui.com/download/#!version=1.12.1&components=111111111110111100000000010000001000100000000001

https://download.jqueryui.com/download
![image](https://user-images.githubusercontent.com/60699975/86593218-031b4900-bfbf-11ea-8fdd-3d0531727157.png)

**Comment by recoverjp** [comment] 2020-07-06 13:57
Same mistake here.

**Comment by recoverjp** [comment] 2020-07-06 14:09
Use https://jqueryui.templersmc.net/

**Comment by ocsross96** [comment] 2020-07-06 16:01
Also have this issue, using @recoverjp's suggestion above

**Comment by RangoSn** [comment] 2020-07-08 23:40
Thanks @recoverjp

**Comment by fnagel** [comment] 2020-07-20 07:47
Duplicate of #359

**Closed by fnagel** 2020-07-20 07:47 UTC
