### ISSUE TITLE
Issue Thread Regarding the 502 Error

### ISSUE THREAD

**Issue by jorydotcom** [jquery/download.jqueryui.com#390] opened 2019-10-23 13:43 UTC
Hi, my name is Jory Burson and I’m a community manager for the OpenJS Foundation.

First, thanks so much to those of you who raised this issue to us via twitter and your networks. I’m sorry that the issue went unnoticed on this repository for so long. 

**Unfortunately, this is not a simple fix.**
The fix for this is part of a longer process of infrastructure improvement and migration, which we’ve only just begun. We are working on resolving this 502 error specifically, but because it is done largely on volunteer time by a few people, we don’t expect that it will move quickly. On behalf of these developers, we appreciate your patience. 

**See #384 & #359 for a workaround.**
@lukasbableck & @superyyao have provided workarounds in these issues. Thank you for taking the time to do that. The download builder source and jQueryUI itself remain available so you should be able to access any tools you need, just not quite as conveniently as we like. 

**Please watch this issue for updates.**
There are a lot of duplicate issues on this repository related to this issue. Most of them will be closed.  

**jQueryUI is an OpenJS Foundation [Emeritus Project.](https://openjsf.org/projects/#emeritus)**
Emeritus projects are those which the maintainers feel have reached or are nearing end-of-life. Emeritus projects have contributed to the ecosystem, but are not necessarily recommended for modern development as there may be more actively maintained choices.

jQueryUI’s core maintainers have moved on from the project and are no longer responding to issues. Please do not tag them. If there is an issue requiring urgent attention you can tag me (@jorydotcom) and I will triage that accordingly. 

jQueryUI is still in use by a significant number of websites, but the download builder isn’t critical to supporting those sites. The OpenJS Foundation is actively helping the jQuery Core team assess and plan next steps here, and will be working to keep the community informed as things progress.

**Comment by fnagel** [comment] 2020-02-18 17:48
@jorydotcom Any news on this?

**Comment by veeraswamyg** [comment] 2020-03-03 06:46
I'm unable to download the Jquery ui, i getting Error 502.

**Comment by JPixDev** [comment] 2020-03-05 18:59
I'm getting an error when I try to download a custom JQuery UI. https://downforeveryoneorjustme.com/ says download.jqueryui.com is down for everyone.

**Comment by Budapresst** [comment] 2020-03-21 11:33
Welcome to Cloudflare!  No support and lots of "fake" 500 errors for resources that are clearly available on the origin server.

**Comment by faisalAkhtar** [comment] 2020-04-21 14:20
Any update on this?

**Comment by d-signet** [comment] 2020-05-19 10:49
"jQueryUI is still in use by a significant number of websites, but the download builder isn’t critical to supporting those sites"

I'm curious what makes you jump to this assertion?

I've got an enterprise-level client to support this week, who are running a stripped-down version of jQueryUI

They require other components (Dialog and it's dependencies) adding to their site's copy of jquery-ui.min.js

I cannot do this without the builder.

The builder is absolutely essential to supporting existing sites for many scenarios.

The repo does not build on windows dev machines because a dependency explicitly blocks it 

 Unsupported platform for modern-syslog@1.1.2: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})

The builder website is essential to many of us.

If it's an Emeritus project, i am curious why a breaking change would be pushed to production. Can it not be reverted?

**Comment by maxvanny2010** [comment] 2020-05-28 21:59
error 502
https://gyazo.com/d73bd7d150d1c98fcd27dd5d5019b3a0

**Comment by uc-media** [comment] 2020-06-11 11:39
Getting the same error

**Comment by wb027** [comment] 2020-06-27 17:08
I see the same error.

**Comment by Wiktor102** [comment] 2020-07-01 15:42
I also have this error.

**Comment by jamesdkelly** [comment] 2020-07-02 10:00
Same problem here - any idea when this might be resolved?

**Comment by Wiktor102** [comment] 2020-07-03 11:56
Some time ago I also had this error but it happened while entering jquery site. After a few minutes, everything returned to normal.

**Comment by PDBrent** [comment] 2020-07-03 14:14
Getting the same 502 error. Is there any alternate source for downloading jquery-ui?

**Comment by PDBrent** [comment] 2020-07-03 14:17
Just tried from this https://jqueryui.com/ - the top right has a link to download the stable version.  Worked ok for me just now

**Comment by wb027** [comment] 2020-07-03 14:26
> Just tried from this https://jqueryui.com/ - the top right has a link to download the stable version. Worked ok for me just now
Custom builder not work.
Any instructions for custom build yourself?

**Comment by lukasbableck** [comment] 2020-07-03 14:28
> > Just tried from this https://jqueryui.com/ - the top right has a link to download the stable version. Worked ok for me just now
> 
> Custom builder not work.
> Any instructions for custom build yourself?

You can use my mirror of the custom download builder.
https://jqueryui.templersmc.net/

**Comment by jamesdkelly** [comment] 2020-07-03 15:42
@lukasbableck Legend! Thank you :)

**Comment by PDBrent** [comment] 2020-07-03 16:28
Thanks! - that worked
Regards,
P Brent

**Comment by sinand99** [comment] 2020-07-05 14:17
So jqueryUI is dead? so much for open source crap

**Comment by acuna-public** [comment] 2020-07-28 00:31
Any news? Do you need any developers help to solve this problem? So sad that my beloved framework dying under my eyes so that we should already need to use a side builders even to download it :(

**Comment by fnagel** [comment] 2020-07-28 22:07
@acuna-public We are working on this issue and there is some slow progress. Feel free to join https://jqueryui-dev.slack.com/ if you want to help!

**Comment by acuna-public** [comment] 2020-07-29 17:41
@fnagel ah yes, I read about your Slack channel in your blog. But do you have any bugs list, because I'm using jQuery and jQuery UI in all my projects and have more than 10 my own plugins for it and have no any problems with it almost 10 years. And another etic moment - jQuery is almost dead too and many of users have finish to use it in favor of other frameworks firstly because it have no updates for nearly than five years, so there's can be looks so strange to see the phrase like "Oh, hey, jQuery is updated? I thought it was dead..." in their eyes... Unfortunately.

**Comment by mgol** [comment] 2020-07-29 18:02
@acuna-public jQuery is far from dead. I’m not sure where you took the 5 years figure from as jQuery has much more frequent updates; the latest version was released in May this year: https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/.

**Comment by acuna-public** [comment] 2020-07-29 18:17
@mgol oh my, I'm so sorry, I means UI :( But yes, it'll be "far from dead", I believe, but I don't see any new projects on jQuery, only in pure JS (people became to write tonns of code only for not to use jQuery, and it's so worry for me), so I can says that it's "far from dead" for legasy projects. BTW, it's not what I want to see.

**Comment by Tzhf** [comment] 2020-09-19 05:41
as an alternative for you can use webpack-jquery-ui

**Comment by OttoG** [comment] 2020-09-22 20:23
> The repo does not build on windows dev machines because a dependency explicitly blocks it
> 
> Unsupported platform for modern-syslog@1.1.2: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})

It does not build out of the box on macOS either, due to the same package. Also, there is a runtime error at the "grunt prepare" stage, which is similar to the one described here: https://timonweb.com/javascript/how-to-fix-referenceerror-primordials-is-not-defined-error/

A workaround for both problems is to create the following "npm-shrinkwrap.json" file before running "npm install":

`{
  "dependencies": {
    "graceful-fs": {
        "version": "4.2.2"
    },
    "modern-syslog": {
        "version": "1.2.0"
    }
  }
}`

After that, "grunt prepare" has to be run with the "--force" flag to avoid errors about wrong dependency versions, but in the end, everything appears to work just fine.

**Comment by Venegrad** [comment] 2020-10-08 16:26
And how i can chose only slider and autocomplete? I dont need 500kb lib..

**Comment by fnagel** [comment] 2020-10-08 21:20
Hey everyone! If you would like to help, test this PR and give some feedback: https://github.com/jquery/download.jqueryui.com/pull/552

**Comment by mgol** [comment] 2020-10-09 22:43
Hey, I've just merged my PR #552 & I deployed it; it has a chance to fix those 502 errors. Now, I don't want to give any guarantees since last time I thought it was fixed it broke within an hour but for now it seems to work. Please test & report issues if you find something is still broken.

**Comment by mgol** [comment] 2020-10-09 22:44
I'll keep this issue open for now until we have some feedback from users of the Download Builder that it now works.

**Comment by Venegrad** [comment] 2020-10-10 12:26
> Hey, I've just merged my PR #552 & I deployed it; it has a chance to fix those 502 errors. Now, I don't want to give any guarantees since last time I thought it was fixed it broke within an hour but for now it seems to work. Please test & report issues if you find something is still broken.
> 
> I'll keep this issue open for now until we have some feedback from users of the Download Builder that it now works.

U are fucking awesome. Thanks

**Comment by alexbovey** [comment] 2020-10-18 10:24
521 error for me today

**Comment by fnagel** [comment] 2020-10-18 10:55
@alexbovey What exactly did you try to use? Do you have a link?

**Comment by alexbovey** [comment] 2020-10-18 11:04
> @alexbovey What exactly did you try to use? Do you have a link?

@fnagel I was trying to build a custom download at https://jqueryui.com/download/ - is that what you mean?

**Comment by fnagel** [comment] 2020-10-19 08:15
@alexbovey Can confirm. We are on it.

**Comment by mgol** [comment] 2020-10-20 11:33
@alexbovey Can you check again? We think we have a fix for that.

**Comment by alexbovey** [comment] 2020-10-20 11:43
> @alexbovey Can you check again? We think we have a fix for that.

@mgol @fnagel Working perfectly now thanks!

**Comment by wb027** [comment] 2020-10-20 14:30
Uncheck all.
Check Draggable and Droppable.

jquery-ui.min.js 331 byte:

```
/*! jQuery UI - v1.12.1 - 2020-10-20
* http://jqueryui.com
* Includes: widget.js, position.js, data.js, keycode.js, scroll-parent.js, unique-id.js, widgets/draggable.js, widgets/droppable.js, widgets/autocomplete.js, widgets/menu.js, widgets/mouse.js
* Copyright jQuery Foundation and other contributors; Licensed MIT */

undefined

```

**Comment by fnagel** [comment] 2020-10-20 14:43
@wb027 Can confirm this. `jquery-ui.js` file is valid though. @mgol Any idea?

**Comment by wb027** [comment] 2020-10-20 15:04
In different configurations.

Accordion only:
```
/*! jQuery UI - v1.12.1 - 2020-10-20
* http://jqueryui.com
* Includes: widget.js, keycode.js, unique-id.js, widgets/accordion.js
* Copyright jQuery Foundation and other contributors; Licensed MIT */

undefined
```

Bounce Effect only:
```
/*! jQuery UI - v1.12.1 - 2020-10-20
* http://jqueryui.com
* Includes: effect.js, effects/effect-bounce.js
* Copyright jQuery Foundation and other contributors; Licensed MIT */

undefined
```

Selectable only:
```
/*! jQuery UI - v1.12.1 - 2020-10-20
* http://jqueryui.com
* Includes: widget.js, widgets/selectable.js, widgets/mouse.js
* Copyright jQuery Foundation and other contributors; Licensed MIT */

undefined
```

**Comment by fnagel** [comment] 2020-10-20 15:50
Seems like all downloads for version 1.12.1 have only `undefined` in the minified file. Downloads for version 1.11.4 and lower work without issues.

**Comment by leonardofaria** [comment] 2020-10-21 00:16
I can confirm @wb027 - tried to create a build with only the accordion and the minified version is broken (the no-minified version is fine)

**Comment by mgol** [comment] 2020-11-04 14:45
It looks like the 502 issue is gone, let me close this issue. Separate problems like the minified file issue should be reported separately. The minified issue is tracked in #559.

**Closed by mgol** 2020-11-04 14:45 UTC
