### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by hellosagar2000** [jquery/download.jqueryui.com#403] opened 2019-12-11 08:53 UTC

**Comment by ITA003** [comment] 2019-12-11 12:03
Me too

**Comment by jazzakash** [comment] 2019-12-23 09:27
I too am facing the same issue.

**Comment by joyfullservice** [comment] 2019-12-23 19:10
I was able to get what I needed at https://jqueryui.com/download/all/

**Comment by fnagel** [comment] 2020-02-18 17:50
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:50 UTC
