### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by pythonnelson** [jquery/download.jqueryui.com#419] opened 2020-02-06 10:38 UTC
Cannot download jqueryui 1.12

**Comment by ph1f1** [comment] 2020-02-06 13:47
Same here..

**Comment by paxter** [comment] 2020-02-06 15:06
Bad gateway error.

**Comment by paxter** [comment] 2020-02-06 15:34
Now it worked. Looks like you need some luck that the target server can handle your download request.

**Comment by ph1f1** [comment] 2020-02-06 15:39
Thx for the hint. I was able to download it now.

**Comment by markhyro123** [comment] 2020-02-07 06:56
same here...

**Comment by atifceylan** [comment] 2020-02-10 06:54
bad gateway error

**Comment by flightltd** [comment] 2020-02-10 10:19
Bad gateway error:
Error 502 Ray ID: 562d57563f3ebb82 • 2020-02-10 10:18:49 UTC

**Comment by elakeduck** [comment] 2020-02-10 12:00
I guess you will need to setup the themeroller / downloader on your own server.
I folled this guide by @THemming:
https://github.com/jquery/download.jqueryui.com/issues/359#issuecomment-530288440

and changed the config.json to the following, because the default one gave my some errors:
`{
	"themeroller": {
		"jquery": "1.7",
		"jqueryUi": "1.12.1"
	},
	"jqueryUi": [
		{
			"version": "1.12.1",
			"dependsOn": "jQuery1.7+",
			"label": "Stable",
			"stable": true
		},
		{
			"version": "1.11.4",
			"dependsOn": "jQuery1.6+",
			"label": "Legacy"
		}
	],
	"jquery": "1.9.1"
}
`

**Comment by fnagel** [comment] 2020-02-18 17:52
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:52 UTC
