### ISSUE TITLE
Download Builder: failing to download a custom package

### ISSUE THREAD

**Issue by mshr-co** [jquery/download.jqueryui.com#360] opened 2019-09-04 19:48 UTC
Hi,

The url for a custom package I'm trying to download is: https://jqueryui.com/download/#!version=1.12.1&components=111000010101110111000000010000000000000000000000

The error from cloudfare upon pressing download:
> Error 502 Ray ID: 511273938961d8a1 • 2019-09-04 19:43:17 UTC
> Bad gateway

Would be grea if this can be looked at, custom packages are an awesome idea as they allow to keep bloat to a minimum.

**Comment by jamescjchan** [comment] 2019-09-06 14:29
Same here. I think it's the same issue mentioned in #359

**Comment by emestanza** [comment] 2019-09-10 14:24
Please help us to fix this issue, I need to generate a custom package ASAP =(

**Comment by erikn69** [comment] 2019-09-11 13:46
+1

**Comment by reForMatt** [comment] 2019-09-11 18:42
+1

**Comment by Raamcy** [comment] 2019-09-12 04:30
+1

**Comment by ksiatka** [comment] 2019-09-12 06:44
+1

**Comment by John-Kjoller** [comment] 2019-09-17 07:17
+1

**Comment by lukasbableck** [comment] 2019-09-18 08:38
You can use my download server to build jqueryUI.

http://templersmc.net:8888/download

**Comment by syousef1975** [comment] 2019-09-21 02:29
Over 2 weeks, still  not working.

**Comment by StefanoAI** [comment] 2019-09-22 08:26
> You can use my download server to build jqueryUI.
> 
> https://jqueryui.templersmc.net/download

502 Bad Gateway

**Comment by VAshkevron71** [comment] 2019-10-04 19:46
October 4th and still not working. Also, the themeroller itself isn't working because it needs to be able to access "parsetheme.css" on download.jqueryui.com.
@StefanoAI Nice of you to provide, but I need the themeroller itself before downloading.

**Comment by jjsibborn** [comment] 2019-10-14 07:17
> October 4th and still not working. Also, the themeroller itself isn't working because it needs to be able to access "parsetheme.css" on download.jqueryui.com.
> @StefanoAI Nice of you to provide, but I need the themeroller itself before downloading.

Same here, thank you for the link, but I require to create a custom theme also - the themeroller is still unavailable

**Comment by cfzumbrun** [comment] 2019-10-14 13:42
Themeroller is failing for me when I start with a blank theme and change anything, like the clickable active state color, with the "Failed to load resource: the server responded with a status of 502 () parsetheme.css:1" error

**Comment by lukasbableck** [comment] 2019-10-17 13:37
@jjsibborn @cfzumbrun 
My server also hosts the themeroller! 
https://jqueryui.templersmc.net/themeroller/

**Comment by jjsibborn** [comment] 2019-10-17 14:08
> @VAshkevron71 @jjsibborn @cfzumbrun
> My server also hosts the themeroller!
> https://jqueryui.templersmc.net/themeroller/

Brilliant, thank you very much!

**Comment by jjsibborn** [comment] 2019-10-17 14:29
> @VAshkevron71 @jjsibborn @cfzumbrun
> My server also hosts the themeroller!
> https://jqueryui.templersmc.net/themeroller/

Unfortunately, when I complete the theme, and click Download, select the version I require and click Download again, I get a 404 Page Cannot Be Found error, second time I go a 503 Gateway error, then a 504 error.
Thank you for trying though, much appreciated

**Comment by lukasbableck** [comment] 2019-10-17 15:26
> > @VAshkevron71 @jjsibborn @cfzumbrun
> > My server also hosts the themeroller!
> > https://jqueryui.templersmc.net/themeroller/
> 
> Unfortunately, when I complete the theme, and click Download, select the version I require and click Download again, I get a 404 Page Cannot Be Found error, second time I go a 503 Gateway error, then a 504 error.
> Thank you for trying though, much appreciated

Thats weird, I don't have that problem. I'm trying to fix that!

**Comment by mrouille** [comment] 2019-10-21 15:24
@lukasbableck I can reproduce the problem that @jjsibborn had. It happens only if I choose a desired version different from 1.12.1. Hope it could help. Thanks anyway for your work.

**Comment by ShoeLace1291** [comment] 2019-11-22 07:53
They still haven't fixed this after more than two months? What a fucking joke.

**Comment by electrotype** [comment] 2019-11-29 09:22
Please fix. This makes the whole project look horrible.

**Comment by mikeduglas** [comment] 2019-12-03 19:05
Still not working, both direct download and temporary mirror.

**Comment by Nikandros** [comment] 2019-12-18 22:20
Is there any alternative to themeroller?

**Comment by VAshkevron71** [comment] 2020-01-03 22:50
It was working for a couple of minutes today. Was actually getting proper responses from "download.jqueryui.com/parsetheme.css", but then it started with the 502 errors again. Wondering if they've exceed certain limits with Cloudflare?

@jjsibborn your mirror site is also returning a 502 error on "jqueryui.templersmc.net" today

**Comment by jjsibborn** [comment] 2020-01-04 08:53
> It was working for a couple of minutes today. Was actually getting proper responses from "download.jqueryui.com/themeroller/parsetheme.css", but then it started with the 502 errors again. Wondering if they've exceed certain limits with Cloudflare?
> 
> @jjsibborn your mirror site is also returning a 502 error on "jqueryui.templersmc.net" today

@VAshkevron71  The mirror site was not created or hosted by me, I just replied to a comment and tried using it myself. 

The jQuery UI support has unfortunately gone down hill since the change of developers. 
We have had to look at redesigning our entire site due to lack of support.

**Comment by edtruant** [comment] 2020-02-18 15:59
I have the same problem here. Is there any solution?
I need to get jQuery UI colors etc corporate compliant (font, colors...).
Please help.

Thanks.

**Comment by fnagel** [comment] 2020-02-18 17:46
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:46 UTC
