### ISSUE TITLE
Can't download Jquery UI 

### ISSUE THREAD

**Issue by AmrAhmedA** [jquery/download.jqueryui.com#461] opened 2020-05-23 07:53 UTC
Error 502 Ray ID: 597d32c43e7bc007 • 2020-05-23 07:52:35 UTC
![image](https://user-images.githubusercontent.com/47694180/82725145-3b025180-9cdb-11ea-93df-1e547c935a36.png)

**Comment by fnagel** [comment] 2020-05-25 08:57
Duplicate of #359

**Closed by fnagel** 2020-05-25 08:57 UTC
