### ISSUE TITLE
Issue downloading version 1.10.4 

### ISSUE THREAD

**Issue by cervantesandres** [jquery/download.jqueryui.com#394] opened 2019-11-05 14:58 UTC
I'm getting a 504 when downloading version 1.10.4. The newer version works fine but I need 1.10.4.

please help.

**Comment by JiffB** [comment] 2019-11-06 17:46
Ah, each day it's own error ;) A moment ago, I tried to download a theme an got a 502 error :/
 Ray ID: 5318e206ce60b78d • 2019-11-06 17:45:45 UTC

**Comment by fnagel** [comment] 2020-02-18 17:49
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:49 UTC
