### ISSUE TITLE
Cannot download theme 1.11.4 version

### ISSUE THREAD

**Issue by KimByrresen** [jquery/download.jqueryui.com#418] opened 2020-02-03 10:11 UTC
JQueryUI Themeroller is broken and has been broken since November 2019? 

Can this please be fixed ?
 
When you try to download the theme it times out with a 504 error.

**Comment by fnagel** [comment] 2020-02-18 17:52
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:52 UTC
