### ISSUE TITLE
 jqueryui -download problem

### ISSUE THREAD

**Issue by mohamadali93** [jquery/download.jqueryui.com#430] opened 2020-03-13 10:11 UTC
I can't download the jqueryui

**Comment by DependencyHell** [comment] 2020-03-19 12:21
Try a stable version : https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip

**Comment by obwang827** [comment] 2020-03-20 03:40
thankyou
Error 502 Ray ID: 576c683e2b7ea354 • 2020-03-20 03:39:39 UTC
Bad gateway
Is still happening

**Comment by DependencyHell** [comment] 2020-03-20 06:30
Yes, they will not fix it soon with the custom downloader, see this post :

https://github.com/jquery/download.jqueryui.com/issues/390

The only way is to build the project on your side to use the downloader...

**Comment by fnagel** [comment] 2020-03-23 20:55
Duplicate of #359

**Closed by fnagel** 2020-03-23 20:55 UTC
