### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by metalox** [jquery/download.jqueryui.com#399] opened 2019-11-21 15:17 UTC
Unable to download Ray ID: 53939085ea0dc29a • 2019-11-21 15:05:55 UTC

**Comment by david-fanin** [comment] 2019-11-26 08:37
Me too !

Error 504 Ray ID: 53ba887b0d5dee89 • 2019-11-26 08:36:10 UTC Gateway time-out

**Comment by Mostafa-Yusuf** [comment] 2019-11-27 13:48
Me too !

Error 504

**Comment by duy4fun** [comment] 2019-11-27 14:47
Ray ID: 53c4e0caab62d96e • 2019-11-27 14:44:05 UTC

**Comment by cosmonoid** [comment] 2019-11-28 08:46
Same here: Ray ID: 53cb1188d972d721 • 2019-11-28 08:45:56 UTC

**Comment by daniel-ilan** [comment] 2019-12-17 11:44
same here. Ray ID: 5468a4dd89156aad • 2019-12-17 11:44:15 UTC

whats up with this? this is going on for weeks...

**Comment by fnagel** [comment] 2020-02-18 17:50
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:50 UTC
