### ISSUE TITLE
Bad gateway error

### ISSUE THREAD

**Issue by agiratech-gokul** [jquery/download.jqueryui.com#460] opened 2020-05-21 10:15 UTC
Cannot download custom jquery ui

**Comment by tinpotnick** [comment] 2020-05-21 11:32
Same for me

**Comment by mills4078** [comment] 2020-05-21 14:49
ditto

**Comment by TBFLash** [comment] 2020-05-21 18:31
Still a problem

**Comment by decadX** [comment] 2020-05-21 19:53
same

**Comment by mrassili** [comment] 2020-05-22 14:55
same

**Comment by mooksz** [comment] 2020-05-22 19:22
ditto

**Comment by larskuerten** [comment] 2020-05-23 00:15
Me 2

**Comment by bounlu** [comment] 2020-05-23 15:36
same

**Comment by fnagel** [comment] 2020-05-25 08:58
Duplicate of #359

**Closed by fnagel** 2020-05-25 08:58 UTC
