### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by dhiyazaidi** [jquery/download.jqueryui.com#443] opened 2020-04-20 14:50 UTC
Browser and Cloudfire(Auckland) are working but, Host is error (download.jqueryui.com).

**Comment by Xites** [comment] 2020-04-21 11:49
Same here
Error 502 Ray ID: 5876e1b9b9b9dbe7 • 2020-04-21 11:49:26 UTC
Bad gateway

**Comment by LuisAlcocer** [comment] 2020-04-21 22:01
I had the same problem, but I used the next address and finally got the file:
https://jqueryui.com/download/all/

**Comment by fnagel** [comment] 2020-04-22 09:05
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:05 UTC
