### ISSUE TITLE
Download Builder gives Error 502

### ISSUE THREAD

**Issue by rafaraca** [jquery/download.jqueryui.com#513] opened 2020-07-20 22:34 UTC
Tried to download and got the download page : https://jqueryui.com/download/
Clicked the download button and then got a :
Error 502 Ray ID: 5b6024ef7f6c09c8 • 2020-07-20 22:33:31 UTC
Bad gateway

Some help, please?

**Comment by atstockland** [comment] 2020-07-21 02:39
At the top of the download page, click on the quick link for "Stable"

**Comment by fnagel** [comment] 2020-07-22 12:02
Duplicate of #359

**Closed by fnagel** 2020-07-22 12:02 UTC
