### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by maxime-lucas** [jquery/download.jqueryui.com#406] opened 2019-12-27 12:51 UTC
Hi,
When I try to download a custom jquery built version, I got this error when I click on the Download button.
For your information, the section "Theme" seems to be broken too.

**Comment by JacobCN** [comment] 2019-12-31 08:58
Error 502 Ray ID: 54db0c760be9ebb5 • 2019-12-31 08:57:55 UTC
Bad gateway

**Comment by andymitchell79** [comment] 2020-01-02 11:43
I'm experiencing the same as of 6:45 am 1/2/2020

**Comment by pcollaog** [comment] 2020-01-02 20:43
Same error

 Error 502 Ray ID: 54ef91399b8ccfb3 • 2020-01-02 20:43:48 UTC

**Comment by fnagel** [comment] 2020-02-18 17:50
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:50 UTC
