### ISSUE TITLE
page not working

### ISSUE THREAD

**Issue by xhevatibraimi** [jquery/download.jqueryui.com#423] opened 2020-02-27 12:53 UTC
i tried to donwload jquery ui 1.10.4 and the following came up
![image](https://user-images.githubusercontent.com/13273178/75446895-95a04180-5968-11ea-83c7-752d9b9ab9a9.png)

**Comment by fnagel** [comment] 2020-02-28 20:23
Duplicate of #359

**Closed by fnagel** 2020-02-28 20:23 UTC
