### ISSUE TITLE
Error 502 Ray ID: 5bbb135a1e979881 • 2020-07-31 23:24:55 UTC Bad gateway

### ISSUE THREAD

**Issue by chriscjamison** [jquery/download.jqueryui.com#523] opened 2020-07-31 23:25 UTC
Attempted to download a custom package of jQuery UI packages but instead of the download, my browser was taken to an error page that listed a 502 error.

**Comment by dekkydog** [comment] 2020-08-01 11:07
Same for me? Bad Gateway?

**Comment by fnagel** [comment] 2020-08-04 12:02
Duplicate of #359

**Closed by fnagel** 2020-08-04 12:02 UTC
