### ISSUE TITLE
Can't download custom jquery

### ISSUE THREAD

**Issue by EricksonRM24** [jquery/download.jqueryui.com#447] opened 2020-04-30 16:42 UTC
I'm currently trying to download a custom jquery for my final assignment (tabs) however I'm just reaching a error page

**Comment by mchuc** [comment] 2020-05-01 05:47
have this same

**Comment by ScottDWagner** [comment] 2020-05-01 17:09
yah getting 503 error as well.

**Comment by rami-lab** [comment] 2020-05-02 07:53
Now 502 error on  cloudflares , seems download.jqueryui.com host is down .

**Comment by wathela** [comment] 2020-05-04 20:49
same here: Error 502

**Comment by fnagel** [comment] 2020-05-15 13:39
Duplicate of #359

**Comment by mchuc** [comment] 2020-05-15 13:40
Welcome  jquery/download.jqueryui.com! 


You are invited to access PLAFYA's Customer Self Service Portal 


 By accessing this portal, you can track your requests online,

access knowledge base and join the community forums.
ACCEPT THE INVITATION



 




Your user name is reply@reply.github.com | You can also click here to accept the invitation 





 



Thank you, PLAFYA Administrator






 








This email has been sent to you&#x28;reply&#x2b;ald3pf2pivhrqc6vhygorsv4zj6jnevbnhhcix2zma&#x40;reply.github.com&#x29; by wizyty&#x40;afya.pl from PLAFYA. Please contact the sender&#x28;wizyty&#x40;afya.pl&#x29; for any clarifications.

**Comment by mchuc** [comment] 2020-05-15 13:40
Welcome  jquery/download.jqueryui.com! 


You are invited to access PLAFYA's Customer Self Service Portal 


 By accessing this portal, you can track your requests online,

access knowledge base and join the community forums.
ACCEPT THE INVITATION



 




Your user name is reply@reply.github.com | You can also click here to accept the invitation 





 



Thank you, PLAFYA Administrator






 








This email has been sent to you&#x28;reply&#x2b;ald3pf6xv5enf3gaueqrnqn4zj6jlevbnhhcix2zma&#x40;reply.github.com&#x29; by wizyty&#x40;afya.pl from PLAFYA. Please contact the sender&#x28;wizyty&#x40;afya.pl&#x29; for any clarifications.

**Closed by fnagel** 2020-05-15 13:39 UTC
