### ISSUE TITLE
can't download jqueryui/themeroller

### ISSUE THREAD

**Issue by Offori** [jquery/download.jqueryui.com#489] opened 2020-06-16 18:23 UTC
Error 502 Ray ID: 5a467a734d74de29 • 2020-06-16 18:08:50 UTC
Bad gateway

**Comment by jtsSTECH** [comment] 2020-06-16 19:10
Same issue.

**Comment by ScottFarrell** [comment] 2020-06-16 20:58
Same issue.

**Comment by Black2developerBR** [comment] 2020-06-17 03:48
Yes, I have the same error.

**Comment by prostoAE** [comment] 2020-06-18 06:26
Same issue.

**Comment by Offori** [comment] 2020-06-18 06:36
If you find any solution, please let me know

**Comment by Offori** [comment] 2020-06-18 06:39
don't really get you please can you be more clear?

**Comment by sd-design** [comment] 2020-06-18 09:22
Same error - Error 502 Ray ID: 5a53f0e2ee360000 • 2020-06-18 09:21:35 UTC

**Comment by RobGvk** [comment] 2020-06-18 21:04
Same issue, come guys WHEN will this be fixed!!!

**Comment by organicon** [comment] 2020-06-18 21:27
Indeed.  Suffering from the same error.  
Seems like a pretty critical bug.

**Comment by SPdowns** [comment] 2020-06-19 14:31
I'm getting bad gateway

**Comment by bpospanov** [comment] 2020-06-22 12:10
https://jqueryui.templersmc.net/download/#!

**Comment by SPdowns** [comment] 2020-06-22 14:53
That link worked for me. Thank you @bpospanov

**Comment by fnagel** [comment] 2020-06-25 11:25
Duplicate of #359

**Closed by fnagel** 2020-06-25 11:25 UTC
