### ISSUE TITLE
Download Builder gives error 502

### ISSUE THREAD

**Issue by IfeOlulesi** [jquery/download.jqueryui.com#438] opened 2020-04-10 10:57 UTC

**Comment by PaulBoundy** [comment] 2020-04-12 04:20
Hi Gurus.
Can this be brought to the attention of someone that can enable the download of the jQueryUI builder.
Thanks

![image](https://user-images.githubusercontent.com/40392215/79060469-7d8c4380-7cc4-11ea-88eb-617b949f7661.png)

**Comment by airplanenoise** [comment] 2020-04-13 12:17
+1

**Comment by goozak** [comment] 2020-04-13 13:10
See [Issue Thread Regarding the 502 Error #390](https://github.com/jquery/download.jqueryui.com/issues/390)

**Comment by nikki2002** [comment] 2020-04-15 11:27
unable to download. 502 error

**Comment by withoutyou0919** [comment] 2020-04-19 04:32
+1

**Comment by fnagel** [comment] 2020-04-22 09:05
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:05 UTC
