### ISSUE TITLE
Error 502 When Try a Custom Download of Jqueryui

### ISSUE THREAD

**Issue by beckynet** [jquery/download.jqueryui.com#465] opened 2020-05-25 08:29 UTC
![jqueryuicustom](https://user-images.githubusercontent.com/2901809/82794338-9b77c700-9e72-11ea-8866-4afade7b0493.PNG)

**Comment by fnagel** [comment] 2020-05-25 08:57
Duplicate of #359

**Closed by fnagel** 2020-05-25 08:57 UTC
