### ISSUE TITLE
I can't downloads builder jQuery UI

### ISSUE THREAD

**Issue by NeerapaTongtitram** [jquery/download.jqueryui.com#452] opened 2020-05-05 10:59 UTC
[When I asked to load it. Will have a problem Error 502 Bad gateway](url)

**Comment by peca11** [comment] 2020-05-05 11:29
Same here

**Comment by The-Bright-Lord** [comment] 2020-05-05 13:31
Bumping this

**Comment by mevsme** [comment] 2020-05-05 23:45
bump

**Comment by nanuit** [comment] 2020-05-06 04:45
bump

**Comment by andersjarl** [comment] 2020-05-06 08:40
bump

**Comment by Erseni** [comment] 2020-05-06 12:03
bump

**Comment by Kirnos** [comment] 2020-05-06 15:53
bump

**Comment by anhaabaete** [comment] 2020-05-06 18:08
Same Here!

**Comment by anhaabaete** [comment] 2020-05-06 18:09
Error 502 Ray ID: 58f4a616ed49f5ff • 2020-05-06 18:08:49 UTC

**Comment by syl666** [comment] 2020-05-06 23:12
Same

**Comment by syl666** [comment] 2020-05-06 23:12
Can anyone recommend an alternative?

**Comment by benadzs** [comment] 2020-05-07 00:59
Hi! You can use this:
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

**Comment by The-Bright-Lord** [comment] 2020-05-07 01:27
Anyone wanting this can download the individual files from the releases zip from

https://github.com/jquery/jquery-ui/releases/tag/1.12.1

You can then use what you want

**Comment by syl666** [comment] 2020-05-07 02:47
Thank YEWS!

**Comment by MrD0llaro** [comment] 2020-05-08 09:47
The ThemeRoller not working too

**Comment by psme222** [comment] 2020-05-08 18:43
same

**Comment by ToniSHernandez** [comment] 2020-05-09 03:18
Same here and it is annoying as I have a project due by next week...

**Comment by faizy7sheikh** [comment] 2020-05-09 14:55
I can not download

**Comment by amots** [comment] 2020-05-09 15:43
same -  failed to download

**Comment by kaggabba** [comment] 2020-05-10 01:44
same problem

**Comment by Dtue** [comment] 2020-05-10 14:05
Same to me!

**Comment by OrunbekK** [comment] 2020-05-10 14:21
Same problem to me, please help

**Comment by Robert-Watts** [comment] 2020-05-11 12:08
Same for me

**Comment by coros-sanborn** [comment] 2020-05-11 15:08
Any progress on this?

**Comment by andrewjohnstrong** [comment] 2020-05-12 04:22
bump

**Comment by hismightiness** [comment] 2020-05-12 07:55
Ugh.

**Comment by der-rote-hund** [comment] 2020-05-12 09:15
Same. Bad gateway…

**Comment by rustykowski** [comment] 2020-05-13 07:17
The jQuery UI project seems to be abandoned. Latest commit 3 years ago. We all have do look for alternatives …

**Comment by fnagel** [comment] 2020-05-15 13:39
Duplicate of #359

**Closed by fnagel** 2020-05-15 13:39 UTC
