### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by matique** [jquery/download.jqueryui.com#493] opened 2020-06-23 11:38 UTC
Hi,

Download of custom jQuery UI package fails with Bad Gateway.
Browser working, Cloudflare (Düsseldorf) working, but Host (download.jqueryui.com) Error.

Best regards,
Martin (matique UG)

**Comment by fnagel** [comment] 2020-06-25 11:27
Duplicate of #359

**Closed by fnagel** 2020-06-25 11:27 UTC
