### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by ragde34** [jquery/download.jqueryui.com#494] opened 2020-06-24 08:58 UTC
Error 502 Ray ID: 5a853b94fa03b2d2 • 2020-06-24 08:55:57 UTC
Bad gateway

**Comment by NahuelAlvarez** [comment] 2020-06-24 12:59
x2

**Comment by SUVENDU125** [comment] 2020-06-25 02:57
jquery  ui builder is not developed properly,while we downloads it shows 502 error

**Comment by fnagel** [comment] 2020-06-25 11:27
Duplicate of #359

**Closed by fnagel** 2020-06-25 11:27 UTC
