### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Heartmanx** [jquery/download.jqueryui.com#538] opened 2020-09-01 08:12 UTC
I couldn't download jqueryui, what can I do to download it

**Comment by amanjainIIITB** [comment] 2020-09-04 06:09
It's still down

**Comment by davecameos** [comment] 2020-09-04 11:13
Same issue. It is still down

**Comment by choisuill** [comment] 2020-09-05 04:13
same issue.....   :(

**Comment by choisuill** [comment] 2020-09-05 04:17
https://jqueryui.com/download/all/
what about here?

**Comment by choisuill** [comment] 2020-09-05 04:21
I don't know if this will help

**Comment by ibrahimgarba** [comment] 2020-09-07 03:03
I cant download it.

**Comment by amarg26** [comment] 2020-09-09 10:39
Jquery team can you please resolve it asap ?

**Comment by fnagel** [comment] 2020-09-21 21:30
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:30 UTC
