### ISSUE TITLE
Error Bad Gateway 

### ISSUE THREAD

**Issue by PLKGIT** [jquery/download.jqueryui.com#410] opened 2020-01-16 21:54 UTC
I have tried to download jQueryUI, but get a bad gateway error message.

**Comment by i-wizard** [comment] 2020-01-17 02:30
I was able to get what I needed at https://jqueryui.com/download/all/

**Comment by fnagel** [comment] 2020-02-18 17:51
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:51 UTC
