### ISSUE TITLE
Error downloading builder

### ISSUE THREAD

**Issue by kelvinwl** [jquery/download.jqueryui.com#396] opened 2019-11-07 12:41 UTC
Hello.
Just now I had an issue trying to download the builder at https://jqueryui.com/download/

**Date**: 2019-11-07 
**Time**: 12:40:00 UTC

**Version**: 1.12.1(Stable, for jQuery1.7+)
**Components**: All

**Comment by kelvinwl** [comment] 2019-11-07 12:43
After I click download I am redirected to the CloudFlare CDN showing HTTP Error 502 (Bad gateway)

**Comment by fnagel** [comment] 2020-02-18 17:49
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:49 UTC
