### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [jquery/download.jqueryui.com#532] opened 2020-08-22 03:10 UTC
I'd had some troubles when I tried to download the archives, the site reports the error 502

**Comment by darenw** [comment] 2020-08-23 18:54
I get 502 also.
 Error 502 Ray ID: 5c7709911a39c627 • 2020-08-23 18:53:36 UTC

**Comment by Screechovski** [comment] 2020-08-24 18:33
Also 
Ray ID: 5c7f293f1e9e78ff • 2020-08-24 18:33:20 UTC

**Comment by vvksamir** [comment] 2020-08-24 20:40
![image](https://user-images.githubusercontent.com/26848633/91094118-38333780-e60f-11ea-8f8a-dd2d79acc9f2.png)
Same here
Ray ID: 5c7fdd35fcff6c62 • 2020-08-24 20:36:12 UTC

**Comment by margaretstout** [comment] 2020-08-25 18:50
Still the same for the last two days. Can someone look into this?

**Comment by Csiliz** [comment] 2020-08-26 21:02
![jQueryUI_Download_error](https://user-images.githubusercontent.com/34108798/91356594-34aad680-e7f0-11ea-99d8-bb477cab0e72.jpg)

**Comment by sir-script** [comment] 2020-08-27 06:47
Me too, Ray ID: 5c93d4571dd40faa • 2020-08-27 06:45:24 UTC

**Comment by Julian-Nash** [comment] 2020-08-27 16:01
Any news on this? Getting the same 502 error

**Comment by Tana1509** [comment] 2020-08-28 12:52
I have the same problem: Error 502 Ray ID: 5c9e2749385f3f04 • 2020-08-28 12:49:39 UTC

**Comment by fnagel** [comment] 2020-08-28 23:32
Duplicate of #359

**Closed by fnagel** 2020-08-28 23:32 UTC
