### ISSUE TITLE
502:Bad Gateway

### ISSUE THREAD

**Issue by felixfreidman** [jquery/download.jqueryui.com#491] opened 2020-06-20 11:16 UTC
Hello everyone, tried to download the JQueryUI, but the request returned 502 error. I tried several times with several browsers, but still didn't get what I wanted.
Thanks!

**Comment by CARAXSoftware** [comment] 2020-06-20 12:04
Same Issue on my side! 502 Error from "download.jqueryui.com".

**Comment by stefan-popescu** [comment] 2020-06-20 14:13
Same here, it no longer works since at least 2 weeks. :(

**Comment by captcurrent** [comment] 2020-06-20 19:36
Well add me to the list.   frustrating

**Comment by tei187** [comment] 2020-06-21 12:33
Sadly, same issue. Stops at cloudflare, host turns out an error for download.jqueryui.com

**Comment by bpospanov** [comment] 2020-06-22 12:10
https://jqueryui.templersmc.net/download/#!

**Comment by stefan-popescu** [comment] 2020-06-22 17:34
Awesome, thanks bpospanov!

**Comment by captcurrent** [comment] 2020-06-23 16:21
Might be a little off topic..... I was hoping this would generate a .js file.....I am not quite sure how to use resulting package

**Comment by bpospanov** [comment] 2020-06-23 16:24
> Might be a little off topic..... I was hoping this would generate a .js file.....I am not quite sure how to use resulting package

there will be plenty files. put all of them into your project and add jquery-ui.min.css and jquery-ui.min.js and include them into your template

**Comment by fnagel** [comment] 2020-06-25 11:26
Duplicate of #359

**Closed by fnagel** 2020-06-25 11:26 UTC
