### ISSUE TITLE
Error 502 Ray ID: 57ea26539a86ff68 • 2020-04-04 09:54:44 UTC Bad gateway

### ISSUE THREAD

**Issue by rmorenopovedano** [jquery/download.jqueryui.com#436] opened 2020-04-04 09:56 UTC

**Comment by goozak** [comment] 2020-04-13 13:10
See [Issue Thread Regarding the 502 Error #390](https://github.com/jquery/download.jqueryui.com/issues/390)

**Comment by fnagel** [comment] 2020-04-22 09:04
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:04 UTC
