### ISSUE TITLE
Jquery ui theme package

### ISSUE THREAD

**Issue by Fazli1994** [jquery/download.jqueryui.com#518] opened 2020-07-27 16:32 UTC
I can't download the Jquery theme package from the link on the bottom. When I click on the download button I get the following error message:
![Capture](https://user-images.githubusercontent.com/64303158/88567169-5c214e80-d04c-11ea-9a2d-1bea8d0d6159.PNG)

Error 502 Ray ID: 5b97be0ddebad3ef • 2020-07-27 16:29:59 UTC
Bad gateway

**Comment by fnagel** [comment] 2020-07-27 19:40
Duplicate of #359

**Closed by fnagel** 2020-07-27 19:40 UTC
