### ISSUE TITLE
Error 502 Ray ID: 58a9f8e3ff128afc • 2020-04-27 16:38:09 UTC Bad gateway

### ISSUE THREAD

**Issue by LittleSmileSun** [jquery/download.jqueryui.com#445] opened 2020-04-27 16:41 UTC
I can't download custom components.

**Comment by mwxgaf** [comment] 2020-04-27 17:08
its my problem too
![jqui](https://user-images.githubusercontent.com/39344217/80400017-6d34b500-88cf-11ea-9dc5-1f9960b70e4e.png)

**Comment by mdmower** [comment] 2020-04-27 17:12
Duplicate of https://github.com/jquery/download.jqueryui.com/issues/444

**Comment by mwxgaf** [comment] 2020-04-27 17:23
I want to download a special theme

**Comment by joandersonalves** [comment] 2020-04-28 21:04
Erro 502, não consigo fazer download!!

**Comment by fnagel** [comment] 2020-05-15 13:38
Duplicate of #359

**Closed by fnagel** 2020-05-15 13:38 UTC
