### ISSUE TITLE
Download For jQuery UI Broken

### ISSUE THREAD

**Issue by rmgreenstreet** [jquery/download.jqueryui.com#444] opened 2020-04-23 18:06 UTC
Windows 10, Chrome Version 80.0.3987.163

![image](https://user-images.githubusercontent.com/50469309/80133552-0330ae80-8563-11ea-8a11-58451b21a755.png)

**Comment by Xtraim** [comment] 2020-04-23 21:53
the same

**Comment by CougarB** [comment] 2020-04-24 06:07
Same for me.

**Comment by yakuz** [comment] 2020-04-24 08:55
Same :(

**Comment by vmorcillo-ada** [comment] 2020-04-24 10:20
me too

**Comment by CougarB** [comment] 2020-04-25 05:38
I figured out a workaround, and I've never done this before, because I'm not a developer. Or I wasn't. In any case, it works from one button on the site, but not on a different button.

On the homepage — https://jqueryui.com/ — there is a Stable button under "Quick Downloads:" to download version 1.12.1. If you click that, you'll download the following:
https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip

However, if you click "Download" on the header tab, it will take you to this URL. 
https://jqueryui.com/download
I believe that this is the roll-your-own page. I selected the same stable version, clicked Toggle All Components, scrolled down and clicked "Download" on the bottom left of the page. This navigates to the following URL — please note that this URL has the word "download" in it twice.
https://download.jqueryui.com/download
This produced the following error message:

Error 502 Ray ID: 5895a47e28a6bb70 • 2020-04-25 05:25:17 UTC
Bad gateway
You-Browser Working
Seattle-Cloudflare-Working
download.jqueryui.com -- Host -- are you bleeding on in the dishwasher Error

**Comment by Zenmaster43** [comment] 2020-04-26 02:52
URL: https://download.jqueryui.com/download

Browser Working
Seattle-Cloudflare-Working
Error 502 Bad Host

Same error for both Safari 13.0.5 and Chrome 80.0.3987.163
MacOS X Catalina

**Comment by rubo77** [comment] 2020-04-26 08:22
there is another way to build the latest jqueryui packages locally:

- use docker: https://github.com/jquery/download.jqueryui.com/issues/384#issuecomment-617183505

**Comment by Stormynights17** [comment] 2020-04-26 21:51
Had the same issue when trying to download from the theme roller, also using Windows 10 and Chrome browser

**Comment by seven-php** [comment] 2020-04-27 07:55
clicking the actual download link for the latest version will work. Try this: [https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip](url)

**Comment by mwxgaf** [comment] 2020-04-28 16:58
I faced this error too.
Ubuntu 16.04 LTS  - Mozilla FireFox latest version.
![jqui](https://user-images.githubusercontent.com/39344217/80515410-2ad6ab00-8997-11ea-8864-dfda02f8678d.png)

**Comment by fnagel** [comment] 2020-05-15 13:38
Duplicate of #359

**Closed by fnagel** 2020-05-15 13:38 UTC

**Comment by Habib-uddin** [comment] 2020-05-17 11:00
![Capture](https://user-images.githubusercontent.com/26386093/82142666-6c040180-9857-11ea-9244-d0dadd667911.PNG)
