### ISSUE TITLE
Getting 502 error

### ISSUE THREAD

**Issue by mr-lfph** [jquery/download.jqueryui.com#550] opened 2020-09-27 04:18 UTC
Getting 502 error while i tried to download jquery ui datepicker 

![jdp](https://user-images.githubusercontent.com/61219914/94355937-5b904d00-00bb-11eb-9b97-b128b0082345.JPG)

**Comment by ALIHAIDER15** [comment] 2020-09-28 11:54
facing same issue

**Comment by DarkCellar** [comment] 2020-09-28 21:00
Same here.

**Comment by fabricioct** [comment] 2020-09-29 16:44
Also with me

**Comment by Glave** [comment] 2020-09-30 03:37
same as me

**Comment by gillesvrstrtn** [comment] 2020-09-30 07:01
same ...!

**Comment by pbson** [comment] 2020-09-30 09:32
same here

**Comment by CipherLab** [comment] 2020-09-30 18:37
Yup... anyone have the datepicker only they'd care to share?

**Comment by ald0acuna** [comment] 2020-09-30 18:38
Same!!

**Comment by Eli-Pan** [comment] 2020-09-30 21:24
Trying to download the theme. Same issue here.

**Comment by m2rivero** [comment] 2020-09-30 22:49
same

**Comment by aal4all** [comment] 2020-10-01 08:47
here also

**Comment by LeopoldoDeLaLlave** [comment] 2020-10-05 13:52
same

**Comment by fnagel** [comment] 2020-10-06 11:07
Duplicate of #359

**Closed by fnagel** 2020-10-06 11:07 UTC
