### ISSUE TITLE
Issues with ThemeRoller loading and downloading

### ISSUE THREAD

**Issue by xobrooklynn** [jquery/download.jqueryui.com#401] opened 2019-12-08 01:34 UTC
When I try to change colors of a theme, it may update at first, but then randomly changes to default in the preview. When I try to download it says "Error 502 Bad gateway" and that it's a server issue, please help

**Comment by fnagel** [comment] 2020-02-18 17:50
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:50 UTC
