### ISSUE TITLE
Error 502 Ray ID: 57cd592d6ad3da96 • 2020-03-31 22:01:20 UTC

### ISSUE THREAD

**Issue by andresnar** [jquery/download.jqueryui.com#433] opened 2020-03-31 22:03 UTC
Error 502 Ray ID: 57cd592d6ad3da96 • 2020-03-31 22:01:20 UTC

**Comment by Artemeey** [comment] 2020-04-01 09:14
https://download.jqueryui.com/download/

Ray ID: 57d131517f0076ad • 2020-04-01 09:13:10 UTC

**Comment by dcartwright07** [comment] 2020-04-08 18:56
I also got the same issue when trying to download.
![Screen Shot 2020-04-08 at 2 50 59 PM](https://user-images.githubusercontent.com/13526857/78822173-9f29ba00-79a8-11ea-872f-360bc7c21857.png)

Error 502 Ray ID: 580e2d12aa869ef7 • 2020-04-08 18:50:48 UTC
Link: https://download.jqueryui.com/download

**Comment by goozak** [comment] 2020-04-13 13:11
See [Issue Thread Regarding the 502 Error #390](https://github.com/jquery/download.jqueryui.com/issues/390)

**Comment by fnagel** [comment] 2020-04-22 09:04
Duplicate of #359

**Closed by fnagel** 2020-04-22 09:04 UTC
