### ISSUE TITLE
Error502 download

### ISSUE THREAD

**Issue by Locking** [jquery/download.jqueryui.com#416] opened 2020-01-27 08:46 UTC

**Comment by HappyEarthDay** [comment] 2020-01-27 17:49
Same issue here, please address soon.  Thank you!

**Error:**
Error 502 Ray ID: 55bc81cd5e5cf4be • 2020-01-27 17:39:37 UTC
Bad gateway

This page (https://download.jqueryui.com/download) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare

What happened?
The web server reported a bad gateway error.

**Comment by NatiVarela** [comment] 2020-01-27 19:18
+1

**Comment by mkeskin** [comment] 2020-01-28 11:24
+1

**Comment by webjonson** [comment] 2020-01-28 19:15
+1

**Comment by dmahoney1213** [comment] 2020-01-29 01:53
+1

**Comment by Daijobou** [comment] 2020-01-29 10:03
Same here. After click on "Download"-button its shows 502 error.

**Comment by Video-VV** [comment] 2020-01-30 06:58
Error 502 (Ray ID: 55cfc3b21989c401 • 2020-01-30 01:45:06 UTC) Bad gateway 
1) You Browser — Working (Saint Petersburg)
2) Cloudflare — Working
3) download.jqueryui.com — Host Error

![bad_gatway_shot](https://user-images.githubusercontent.com/13081699/73427059-fc6d1380-4346-11ea-9608-ce00c1f7bf81.PNG)

**Comment by Daijobou** [comment] 2020-01-30 09:41
This isse exists since November 2019, so probably jQueryUI is dead and nobody cares anymore?

**Comment by KimByrresen** [comment] 2020-02-03 10:08
When will this be fixed?

Cannot download 1.11.4 version

**Comment by fnagel** [comment] 2020-02-18 17:52
Duplicate of #359

**Closed by fnagel** 2020-02-18 17:52 UTC
