### ISSUE TITLE
Gateway error

### ISSUE THREAD

**Issue by flo-rider** [jquery/download.jqueryui.com#536] opened 2020-08-29 20:40 UTC
This URL throws a gateway error when clicking download: https://jqueryui.com/download/#!version=1.12.1&components=000000010000000000000010000000000000000000000000

**Comment by zoldos** [comment] 2020-08-30 07:12
Yup, I'm getting it too on Firefox and Opera and again when I turned my VPN off. :(

**Comment by sebastian-alfers** [comment] 2020-08-30 15:58
👍

**Comment by mpalladinru** [comment] 2020-08-31 01:06
Are you ever going to fix this? It's not working for more than day. No any VPN works.

**Comment by JeanCaEscalante** [comment] 2020-08-31 01:37
This URL throws a gateway error when clicking download: https://jqueryui.com/download/#!version=1.12.1&components=110000010001000000100000100000000000000000000000

**Comment by mattyonice** [comment] 2020-08-31 02:54
Facing same issue. Tried to access with Chrome.

**Comment by tiyberius** [comment] 2020-09-01 04:12
Same here. I assumed it was because I was trying to download from New Zealand, but glad to know that other people are having issues too

**Comment by whiplashoo** [comment] 2020-09-01 05:59
Same issue here, 502 gateway error.

**Comment by richard-edgecreative** [comment] 2020-09-02 08:46
I have tried yesterday and today (2nd August 2020) and getting the same error.

**Comment by Lueton** [comment] 2020-09-02 18:57
same here

**Comment by bartmelton** [comment] 2020-09-03 01:32
ditto

**Comment by fnagel** [comment] 2020-09-21 21:30
Duplicate of #359

**Closed by fnagel** 2020-09-21 21:30 UTC
