### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by vosidiy** [jquery/download.jqueryui.com#517] opened 2020-07-26 12:05 UTC
![image](https://user-images.githubusercontent.com/36692987/88478490-3ddf2400-cf62-11ea-8801-16adcf545595.png)

**Comment by sagrael** [comment] 2020-07-27 11:35
Error 502 Ray ID: 5b960e693e24dfa5 • 2020-07-27 11:35:19 UTC
Bad gateway

**Comment by ddison** [comment] 2020-07-27 14:18
Same issue (Cloudflare for me was Chicago) but I get the Host error trying to download any version of theme.

**Comment by fnagel** [comment] 2020-07-27 19:40
Duplicate of #359

**Closed by fnagel** 2020-07-27 19:40 UTC
