### ISSUE TITLE
Error 504 (cloudflare screen) on https://download.jqueryui.com/download

### ISSUE THREAD

**Issue by davibertolini** [jquery/download.jqueryui.com#422] opened 2020-02-18 22:52 UTC
Hi, we are trying to download themes build on the themeroller (https://jqueryui.com/themeroller/). Regardless of which theme (custom or preset) and regardless of which version (1.12.1 or 1.11.4) with all options enabled or some, the actual download does not work, throwing a 504 error by CloudFlare.

![Screen Shot 2020-02-18 at 19 44 49](https://user-images.githubusercontent.com/17347794/74784650-2602c600-5287-11ea-8115-906cd9b9ae7d.jpg)

Tried on Chrome (latest) Firefox ESR (latest). Tried from the following location: Chile / Mexico

When tried with VPN on USA gives a 502 Error:

![Screen Shot 2020-02-18 at 19 50 43](https://user-images.githubusercontent.com/17347794/74785027-0f10a380-5288-11ea-8eb0-50f2a90063da.jpg)

Sample link NOT working: https://jqueryui.com/download/#!version=1.11.4&zThemeParams=5d00000100db05000000000000003d8888d844329a8dfe02723de3e5700bbb34ecf36cdef1e1654faa0015427bdb9eb45ebe89aaede0ec5f0d92417fcc6551ce804ff46bf543167700d2cf4e583f2515147aacb86ffa11c0e5097532fb3e7cf9d0b8bef289edd132644d7fb35383d0afe322f177a5bd8901d9993719f13d3a350661be992db985c43f45641a488961243e16655eb9b3d5372d01d7c42d6a5bd7a66be399a446f0bfe46a6cf1e73ec6f33ff8d839172028c5c56d0d44fe7ffeb5243bb9e15671de0f3a3ba006f0aa15a8ce5acf177a55cce97b332f7c14c07ffffe7eb32a94b7688b066a659b965947d0061c4dfe1e8e02fcfbdabb531de84905a7e217151614d91332eaf2db191039c555eac7b3f5992edc1d3836f53f977c7ece8ea39c66ee8b973f459fc97cbe44e5ec56e47d4c949dc99d4b6afb8031c2bf919ff4a994f2681c26ae3c0b6bb0bd98d8768de1bc6c25eb1bf96aa4a223aa90e266c9c39536cb3b9d991d4820ad23be3ccb334d22475f46c56ea98ea75a98e6f64dfd6baab2a805b255d9b89a2982ea49492c43bdfbf866edfd11eba6f543e9dfa414ae89fdebe35db9ea98ab2af51af0e8706c5ef11a56eb1960a3cf3fd2015c6036d3590929ce0aecc26c2e9b657a00f838c00944ffd7460db6

I've already seen issues https://github.com/jquery/download.jqueryui.com/issues/420 and https://github.com/jquery/download.jqueryui.com/issues/387 which state are closed, but...

**Comment by davibertolini** [comment] 2020-02-19 12:32
Tried today with Opera browser, got a ERR_CONNECTION_CLOSED. 

Tried again with Firefox, got Gateway Timeout 504. 

![Screen Shot 2020-02-19 at 09 28 09](https://user-images.githubusercontent.com/17347794/74834521-559ee600-52fa-11ea-8e2a-a7c1aca9ff29.jpg)

Still can't download themes :( https://download.jqueryui.com/download is still unavailable

Please inform if this is a known issue or if any solution might be available.

**Comment by netquik** [comment] 2020-02-19 16:58
Same problem here since months. No way to save a subset library.

**Comment by cblessing** [comment] 2020-02-20 17:07
I was having the same problem (error 504). Every once in a while I get an "INVALID RESPONSE" error, but mostly it's the 504.

![image](https://user-images.githubusercontent.com/3458149/74959884-39fe1300-53c0-11ea-925b-ca489f5ca21d.png)

**Comment by fnagel** [comment] 2020-02-21 16:53
Duplicate of #359

**Closed by fnagel** 2020-02-21 16:53 UTC
