### ISSUE TITLE
Error 502 

### ISSUE THREAD

**Issue by lemospace** [jquery/download.jqueryui.com#508] opened 2020-07-12 20:37 UTC
Bad gateway

Can't download and can't select themes

**Comment by ruud-kok** [comment] 2020-07-13 13:50
I also get a 502 error, when downloading from here: https://jqueryui.com/download/#!version=1.12.1&components=100000010000000000000000010010000000000000000000

**Comment by endyknov** [comment] 2020-07-16 03:38
I can't dowload too. Please fix.

**Comment by LasyCoder** [comment] 2020-07-16 15:39
i can't  download too. it shows 502 error

**Comment by AssassinGT** [comment] 2020-07-19 23:57
Error 502:host error. Even with vpn .it's not accessible.

**Comment by fnagel** [comment] 2020-07-20 07:46
Duplicate of #359

**Closed by fnagel** 2020-07-20 07:46 UTC
