### ISSUE TITLE
> You can use my download server to build jqueryUI.

### ISSUE THREAD

**Issue by KPTousey** [jquery/download.jqueryui.com#534] opened 2020-08-27 23:37 UTC
> You can use my download server to build jqueryUI.
> 
> https://jqueryui.templersmc.net/download

502 Bad Gateway

_Originally posted by @StefanoAI in https://github.com/jquery/download.jqueryui.com/issues/360#issuecomment-533860665_

I get a server down error when attempting this connection.
8/27/20pm.

**Comment by fnagel** [comment] 2020-08-28 23:33
Duplicate of #359

**Closed by fnagel** 2020-08-28 23:33 UTC
