### ISSUE TITLE
1.12.1(Stable, for jQuery1.7+) dowload problem.

### ISSUE THREAD

**Issue by an80x86** [jquery/download.jqueryui.com#446] opened 2020-04-29 23:37 UTC
1.12.1(Stable, for jQuery1.7+) dowload problem.

**Comment by dyslexicanaboko** [comment] 2020-05-03 18:41
I have the same problem. Been trying since last night. I just keep getting Bad gateway error which is happening on the download.jqueryui.com side.

**Comment by mirasoldavila13** [comment] 2020-05-06 22:13
same

**Comment by fnagel** [comment] 2020-05-15 13:39
Duplicate of #359

**Closed by fnagel** 2020-05-15 13:39 UTC
