### ISSUE TITLE
#BlackLiveMatter... but users who wish to download jQueryUI don't

### ISSUE THREAD

**Issue by LukeTOBrien** [jquery/download.jqueryui.com#510] opened 2020-07-13 16:56 UTC
I have just noticed somebody has changed the website to add a BlackLifeMatters banner, but the download button still gives a 500 error 👿

**Comment by fnagel** [comment] 2020-07-20 07:42
Duplicate of #359

**Closed by fnagel** 2020-07-20 07:42 UTC

**Comment by uchuugaka** [comment] 2020-07-21 02:34
Highly inappropriate.
