### ISSUE TITLE
Error 502 - Bad gateway

### ISSUE THREAD

**Issue by cassianoheitor1993** [jquery/download.jqueryui.com#516] opened 2020-07-24 21:20 UTC
download.jqueryui.com - Host - Error
![image](https://user-images.githubusercontent.com/68757208/88436239-460c5780-cdda-11ea-8ab9-fd79ea682d37.png)

**Comment by gwyneblaidd** [comment] 2020-07-25 00:40
Hi to all!

I have the same issue

![image](https://user-images.githubusercontent.com/6455432/88444979-84c8fe80-ce28-11ea-8df4-aafb913d45d6.png)

**Comment by gwyneblaidd** [comment] 2020-07-25 00:41
I have error when trying to download jqueryui from builder.

**Comment by gwyneblaidd** [comment] 2020-07-25 00:49
@cassianoheitor1993 use this link I have found in another topic

https://jqueryui.templersmc.net/download/

**Comment by fnagel** [comment] 2020-07-27 19:40
Duplicate of #359

**Closed by fnagel** 2020-07-27 19:40 UTC
